In [1]:
import pandas as pd
import numpy as np
from datetime import timedelta

11_02 --> 17_02

Read the csv files

In [2]:
data_courant = pd.read_csv("De 11_02 à 17_02 2022\Courant\COURANT QA.csv", encoding='utf-16',sep="\t") 
data_Debit_eau = pd.read_csv("De 11_02 à 17_02 2022\Débit Eau\DEBIT EAU QA.csv",encoding='utf-16',sep="\t") 
data_Debit_solide = pd.read_csv("De 11_02 à 17_02 2022\Débit Solide\DEBIT SOLIDE QA.csv",encoding='utf-16', sep= '\t') 
data_refus_tamis = pd.read_excel("De 11_02 à 17_02 2022\Refus Tamis\TB_D80_et_performances_Usine_Février_2022.xlsx")
data_puissance = pd.read_csv("De 11_02 à 17_02 2022\Puissance\PUISSANCE QA.csv",encoding='utf-16',sep="\t")

In [3]:
print("-----------------Courant-------------------------------")
print(data_courant)
print("-----------------Debit eau-------------------------------")
print(data_Debit_eau)
print("-----------------Debit solide-------------------------------")
print(data_Debit_solide)
print("-----------------Refus tamis-------------------------------")
print(data_refus_tamis.head(10))
print("-----------------Puissance-------------------------------")
print(data_puissance)

-----------------Courant-------------------------------
               COURANT Time    COURANT ValueY
0       11/02/2022 00:00:00  69,7350311279297
1       11/02/2022 00:00:00  68,7320556640625
2       11/02/2022 00:00:01  64,6725997924805
3       11/02/2022 00:00:01  60,7117309570313
4       11/02/2022 00:00:02  61,8302955627441
...                     ...               ...
831950  17/02/2022 15:00:53  63,2038459777832
831951  17/02/2022 15:00:54  68,2458801269531
831952  17/02/2022 15:00:54  66,4371337890625
831953  17/02/2022 15:00:55  68,4056701660156
831954  17/02/2022 15:00:55  71,5267639160156

[831955 rows x 2 columns]
-----------------Debit eau-------------------------------
             DEBIT EAU Time  DEBIT EAU ValueY
0       11/02/2022 00:00:01  9,69690418243408
1       11/02/2022 00:00:03  9,80179405212402
2       11/02/2022 00:00:05  9,86689853668213
3       11/02/2022 00:00:07  9,80541133880615
4       11/02/2022 00:00:09  9,86689853668213
...                     ...               ...
207515  17/02/2022 14:59:56  9,54137706756592
207516  17/02/2022 14:59:58  9,41478633880615
207517  17/02/2022 15:00:00  9,26287651062012
207518  17/02/2022 15:00:02  9,10011577606201
207519  17/02/2022 15:00:04  8,95543956756592

[207520 rows x 2 columns]
-----------------Debit solide-------------------------------
                SOLIDE Time     SOLIDE ValueY          SP_INT Time  \
0       11/02/2022 00:00:01  116,418907165527  11/02/2022 00:00:01
1       11/02/2022 00:00:03  116,554542541504  11/02/2022 00:00:03
2       11/02/2022 00:00:05  116,581672668457  11/02/2022 00:00:05
3       11/02/2022 00:00:07  116,111473083496  11/02/2022 00:00:07
4       11/02/2022 00:00:09  114,800346374512  11/02/2022 00:00:09
...                     ...               ...                  ...
207879  17/02/2022 15:00:42  107,846862792969                  NaN
207880  17/02/2022 15:00:44  106,996887207031                  NaN
207881  17/02/2022 15:00:46  106,391059875488                  NaN
207882  17/02/2022 15:00:48  105,532043457031                  NaN
207883  17/02/2022 15:00:50  104,501235961914                  NaN

        SP_INT ValueY
0               115.0
1               115.0
2               115.0
3               115.0
4               115.0
...               ...
207879            NaN
207880            NaN
207881            NaN
207882            NaN
207883            NaN

[207884 rows x 4 columns]
-----------------Refus tamis-------------------------------
   Unnamed: 0           Unnamed: 1 Unnamed: 2                Unnamed: 3
0         NaN                  NaN        NaN                       NaN
1         NaN                Jours      Poste  Refus Tamis +500 en % QA
2         NaN                  NaN        NaN                       NaN
3         NaN  2022-02-01 00:00:00          1                 26.205511
4         NaN                  NaN          2                 27.455296
5         NaN                  NaN          3                 29.126214
6         NaN  2022-02-02 00:00:00          1                 18.786127
7         NaN                  NaN          2                 23.913043
8         NaN                  NaN          3                 25.235634
9         NaN  2022-02-03 00:00:00          1                 21.499449
-----------------Puissance-------------------------------
             PUISSANCE Time  PUISSANCE ValueY
0       11/02/2022 00:00:00  627,761962890625
1       11/02/2022 00:00:00   589,28466796875
2       11/02/2022 00:00:01  554,480285644531
3       11/02/2022 00:00:01  520,521240234375
4       11/02/2022 00:00:02  530,111389160156
...                     ...               ...
831681  17/02/2022 15:00:53  541,887756347656
831682  17/02/2022 15:00:54  588,847412109375
831683  17/02/2022 15:00:54  569,608825683594
831684  17/02/2022 15:00:55   602,02294921875
831685  17/02/2022 15:00:55   666,88037109375

[831686 rows x 2 columns]

Function to pre-process "refus tamis"

In [2]:
def process_refu_tamis(data):
    data.dropna(how='all',inplace=True)
    del data["Unnamed: 0"]
    data.rename(columns={'Unnamed: 1':"Jours", 'Unnamed: 2':"Poste",'Unnamed: 3':"Refus Tamis +500 en % QA"}, inplace=True)
    data.drop(index=1,inplace=True)
    for i,line in enumerate(data.index):
        if data.iloc[i]["Jours"] is np.nan:
            data.iloc[i]["Jours"] = data.iloc[i-1]["Jours"]

In [5]:
process_refu_tamis(data_refus_tamis)
data_refus_tamis

                  Jours Poste Refus Tamis +500 en % QA
3   2022-02-01 00:00:00     1                26.205511
4   2022-02-01 00:00:00     2                27.455296
5   2022-02-01 00:00:00     3                29.126214
6   2022-02-02 00:00:00     1                18.786127
7   2022-02-02 00:00:00     2                23.913043
..                  ...   ...                      ...
85  2022-02-28 00:00:00     2                33.198507
86  2022-02-28 00:00:00     3                28.062157
87              MOYENNE   NaN                24.345225
88              MOYENNE   NaN                15.627498
89              MOYENNE   NaN                33.198507

[87 rows x 3 columns]

Print the types of every column in our data

In [6]:
print(data_courant.dtypes)
print(data_Debit_eau.dtypes)
print(data_Debit_solide.dtypes)
print(data_refus_tamis.dtypes)
print(data_puissance.dtypes)

COURANT Time      object
COURANT ValueY    object
dtype: object
DEBIT EAU Time      object
DEBIT EAU ValueY    object
dtype: object
SOLIDE Time       object
SOLIDE ValueY     object
SP_INT Time       object
SP_INT ValueY    float64
dtype: object
Jours                       object
Poste                       object
Refus Tamis +500 en % QA    object
dtype: object
PUISSANCE Time      object
PUISSANCE ValueY    object
dtype: object

Convert the types from object to date_time

In [7]:
data_courant['COURANT Time'] = pd.to_datetime(data_courant['COURANT Time'], format="%d/%m/%Y %H:%M:%S")
data_Debit_eau['DEBIT EAU Time'] = pd.to_datetime(data_Debit_eau['DEBIT EAU Time'], format="%d/%m/%Y %H:%M:%S")
data_Debit_solide['SOLIDE Time'] = pd.to_datetime(data_Debit_solide['SOLIDE Time'], format="%d/%m/%Y %H:%M:%S")
data_puissance['PUISSANCE Time'] = pd.to_datetime(data_puissance['PUISSANCE Time'], format="%d/%m/%Y %H:%M:%S")
#data_refus_tamis['Jours'] = pd.to_datetime(data_refus_tamis['Jours'], format="%Y/%m/%d %H:%M:%S")

In [8]:
print(data_courant.dtypes)
print(data_Debit_eau.dtypes)
print(data_Debit_solide.dtypes)
print(data_puissance.dtypes)
#print(data_refus_tamis.dtypes)

COURANT Time      datetime64[ns]
COURANT ValueY            object
dtype: object
DEBIT EAU Time      datetime64[ns]
DEBIT EAU ValueY            object
dtype: object
SOLIDE Time      datetime64[ns]
SOLIDE ValueY            object
SP_INT Time              object
SP_INT ValueY           float64
dtype: object
PUISSANCE Time      datetime64[ns]
PUISSANCE ValueY            object
dtype: object

Replace the "," by "."

In [9]:
data_courant["COURANT ValueY"] = data_courant["COURANT ValueY"].apply(lambda x: x.replace("," , "."))
data_Debit_eau["DEBIT EAU ValueY"] = data_Debit_eau["DEBIT EAU ValueY"].apply(lambda x: x.replace("," , "."))
data_Debit_solide["SOLIDE ValueY"] = data_Debit_solide["SOLIDE ValueY"].apply(lambda x: x.replace("," , "."))
data_puissance["PUISSANCE ValueY"] = data_puissance["PUISSANCE ValueY"].apply(lambda x: x.replace("," , "."))

Change the type from "object" to "float" for the Value Columns

In [10]:
data_courant["COURANT ValueY"] = data_courant["COURANT ValueY"].astype(float)
data_Debit_eau["DEBIT EAU ValueY"] = data_Debit_eau["DEBIT EAU ValueY"].astype(float)
data_Debit_solide["SOLIDE ValueY"] = data_Debit_solide["SOLIDE ValueY"].astype(float)
data_puissance["PUISSANCE ValueY"] = data_puissance["PUISSANCE ValueY"].astype(float)

Shape of every csv file

In [11]:
print(data_courant.shape)
print(data_Debit_eau.shape)
print(data_Debit_solide.shape)
print(data_refus_tamis.shape)
print(data_puissance.shape)

(831955, 2)
(207520, 2)
(207884, 4)
(87, 3)
(831686, 2)

The max and the min

In [12]:
print("Courant : ")
print(data_courant['COURANT Time'].min())
print(data_courant['COURANT Time'].max())
print("Débit Eau")
print(data_Debit_eau['DEBIT EAU Time'].min())
print(data_Debit_eau['DEBIT EAU Time'].max())
print("Débit Solide")
print(data_Debit_solide['SOLIDE Time'].min())
print(data_Debit_solide['SOLIDE Time'].max())
print("Puissance")
print(data_puissance['PUISSANCE Time'].min())
print(data_puissance['PUISSANCE Time'].max())

Courant :
2022-02-11 00:00:00
2022-02-17 15:00:55
Débit Eau
2022-02-11 00:00:01
2022-02-17 15:00:04
Débit Solide
2022-02-11 00:00:01
2022-02-17 15:00:50
Puissance
2022-02-11 00:00:00
2022-02-17 15:00:55

In [13]:
interv2 = data_courant[data_courant["COURANT Time"].between(pd.to_datetime("2022-02-17 11:10:00"),pd.to_datetime("2022-02-17 11:11:00"))]
print(interv2["COURANT ValueY"].mean())
print(interv2.shape[0])

65.16948268452629
122

In [6]:
def second_to_minute(data):
    columns = data.columns
    time_start = pd.to_datetime("2022-02-11 00:00:00")
    time_end = pd.to_datetime("2022-02-17 15:00:00")
    list_time = []
    list_value = []
    list_value_2 = []
    while(time_start <= time_end):
        interv = data[data[columns[0]].between(time_start,time_start + timedelta(minutes=1))]
        if interv.shape[0] == 0:
            list_value.append(float("nan"))
        else:
            list_value.append(interv[columns[1]].mean())
        list_time.append(time_start)
        if len(columns) == 4:
            list_value_2.append(interv[columns[3]].mean())
        time_start = time_start + timedelta(minutes=1)
    if len(columns) == 2:
        new_data = pd.DataFrame(data=zip(list_time,list_value),columns=[columns[0],columns[1]])
    elif len(columns) == 4:
        new_data = pd.DataFrame(data=zip(list_time,list_value,list_value_2),columns=[columns[0],columns[1],columns[3]])
    return new_data

In [17]:
new_data_courant = second_to_minute(data_courant)
new_data_debit_eau = second_to_minute(data_Debit_eau)
new_data_debit_solide = second_to_minute(data_Debit_solide)
new_data_puissance = second_to_minute(data_puissance)

In [18]:
print(new_data_courant)
print(new_data_debit_eau)
print(new_data_debit_solide)
print(new_data_puissance)

            COURANT Time  COURANT ValueY
0    2022-02-11 00:00:00       65.442617
1    2022-02-11 00:01:00       65.784166
2    2022-02-11 00:02:00       65.831569
3    2022-02-11 00:03:00       64.970144
4    2022-02-11 00:04:00       65.341595
...                  ...             ...
9536 2022-02-17 14:56:00       66.063068
9537 2022-02-17 14:57:00       65.189325
9538 2022-02-17 14:58:00       66.403390
9539 2022-02-17 14:59:00       66.516785
9540 2022-02-17 15:00:00       66.288485

[9541 rows x 2 columns]
          DEBIT EAU Time  DEBIT EAU ValueY
0    2022-02-11 00:00:00          9.366681
1    2022-02-11 00:01:00          8.775439
2    2022-02-11 00:02:00          9.686415
3    2022-02-11 00:03:00          9.813006
4    2022-02-11 00:04:00          9.897039
...                  ...               ...
9536 2022-02-17 14:56:00          9.216323
9537 2022-02-17 14:57:00          9.203489
9538 2022-02-17 14:58:00          9.226007
9539 2022-02-17 14:59:00          9.297878
9540 2022-02-17 15:00:00          9.106144

[9541 rows x 2 columns]
             SOLIDE Time  SOLIDE ValueY  SP_INT ValueY
0    2022-02-11 00:00:00     115.298274          115.0
1    2022-02-11 00:01:00     113.518156          115.0
2    2022-02-11 00:02:00     113.878942          115.0
3    2022-02-11 00:03:00     117.350561          115.0
4    2022-02-11 00:04:00     113.183894          115.0
...                  ...            ...            ...
9536 2022-02-17 14:56:00     111.649853            NaN
9537 2022-02-17 14:57:00     110.982478            NaN
9538 2022-02-17 14:58:00     109.076022            NaN
9539 2022-02-17 14:59:00     109.423127            NaN
9540 2022-02-17 15:00:00     111.625476            NaN

[9541 rows x 3 columns]
          PUISSANCE Time  PUISSANCE ValueY
0    2022-02-11 00:00:00        559.952023
1    2022-02-11 00:01:00        562.290662
2    2022-02-11 00:02:00        562.912594
3    2022-02-11 00:03:00        557.878828
4    2022-02-11 00:04:00        561.615206
...                  ...               ...
9536 2022-02-17 14:56:00        564.337326
9537 2022-02-17 14:57:00        558.512230
9538 2022-02-17 14:58:00        569.896756
9539 2022-02-17 14:59:00        569.889818
9540 2022-02-17 15:00:00        573.881831

[9541 rows x 2 columns]

Rename the columns of Time

In [32]:
new_data_courant.rename(columns={"COURANT Time": "Time"}, inplace=True)
new_data_debit_eau.rename(columns={"DEBIT EAU Time": "Time"}, inplace=True)
new_data_debit_solide.rename(columns={"SOLIDE Time": "Time"}, inplace=True)
new_data_puissance.rename(columns={"PUISSANCE Time": "Time"}, inplace=True)

Merge all this data(column) in on pandas dataframe

In [33]:
data_11_02_a_17_02 = pd.merge(pd.merge(new_data_courant,new_data_debit_eau,on='Time'),pd.merge(new_data_debit_solide,new_data_puissance,on='Time'),on="Time")

In [34]:
data_11_02_a_17_02

,Time,COURANT ValueY,DEBIT EAU ValueY,SOLIDE ValueY,SP_INT ValueY,PUISSANCE ValueY
0,2022-02-11 00:00:00,65.442617,9.366681,115.298274,115.0,559.952023
1,2022-02-11 00:01:00,65.784166,8.775439,113.518156,115.0,562.290662
2,2022-02-11 00:02:00,65.831569,9.686415,113.878942,115.0,562.912594
3,2022-02-11 00:03:00,64.970144,9.813006,117.350561,115.0,557.878828
4,2022-02-11 00:04:00,65.341595,9.897039,113.183894,115.0,561.615206
...,...,...,...,...,...,...
9536,2022-02-17 14:56:00,66.063068,9.216323,111.649853,NaN,564.337326
9537,2022-02-17 14:57:00,65.189325,9.203489,110.982478,NaN,558.512230
9538,2022-02-17 14:58:00,66.403390,9.226007,109.076022,NaN,569.896756
9539,2022-02-17 14:59:00,66.516785,9.297878,109.423127,NaN,569.889818
9540,2022-02-17 15:00:00,66.288485,9.106144,111.625476,NaN,573.881831

In [36]:
data_11_02_a_17_02.to_csv("data_11_02_a_17_02.csv")

15_09 --> 20_10

Read csv files

In [37]:
data_courant_1_10 = pd.read_csv("De 15_09 à 20_10 2022\Courant\COURANT QA 1 - 10.csv", encoding='utf-16',sep="\t") 
data_courant_10_20_10 = pd.read_csv("De 15_09 à 20_10 2022\Courant\COURANT QA 10 - 20  10.csv", encoding='utf-16',sep="\t") 
data_courant_15_9_1_10 = pd.read_csv("De 15_09 à 20_10 2022\Courant\COURANT QA 15 9  - 1 10.csv", encoding='utf-16',sep="\t") 

data_Debit_eau_1_20_10 = pd.read_csv("De 15_09 à 20_10 2022\Débit Eau\DEBIT EAU QA 1 - 20 10.csv",encoding='utf-16',sep="\t") 
data_Debit_eau_15_9_1_10 = pd.read_csv("De 15_09 à 20_10 2022\Débit Eau\DEBIT EAU QA 15 9 - 1 10.csv",encoding='utf-16',sep="\t") 

data_Debit_solide_1_20_10 = pd.read_csv("De 15_09 à 20_10 2022\Débit Solide\DEBIT SOLIDE QA 1 - 20 10.csv",encoding='utf-16', sep= '\t') 
data_Debit_solide_15_9_1_10 = pd.read_csv("De 15_09 à 20_10 2022\Débit Solide\DEBIT SOLIDE QA 15 9 - 1 10.csv",encoding='utf-16', sep= '\t') 

data_refus_tamis_octobre = pd.read_excel("De 15_09 à 20_10 2022\Refus Tamis\TB_D80_et_performances_Usine_Octobre_2022.xlsx")
data_refus_tamis_septembre = pd.read_excel("De 15_09 à 20_10 2022\Refus Tamis\TB_D80_et_performances_Usine_Septembre_2022.xlsx")

data_puissance_QA_1 = pd.read_csv("De 15_09 à 20_10 2022\Puissance\P QA 1.csv",encoding='utf-16',sep="\t") 
data_puissance_QA_2 = pd.read_csv("De 15_09 à 20_10 2022\Puissance\P QA 2.csv",encoding='utf-16',sep="\t") 
data_puissance_QA_3 = pd.read_csv("De 15_09 à 20_10 2022\Puissance\P QA 3.csv",encoding='utf-16',sep="\t") 
data_puissance_QA_4 = pd.read_csv("De 15_09 à 20_10 2022\Puissance\P QA 4.csv",encoding='utf-16',sep="\t") 
data_puissance_QA_5 = pd.read_csv("De 15_09 à 20_10 2022\Puissance\P QA 5.csv",encoding='utf-16',sep="\t") 
data_puissance_QA_6 = pd.read_csv("De 15_09 à 20_10 2022\Puissance\P QA 6.csv",encoding='utf-16',sep="\t") 
data_puissance_QA_7 = pd.read_csv("De 15_09 à 20_10 2022\Puissance\P QA 7.csv",encoding='utf-16',sep="\t")

In [49]:
print("-----------------Courant-------------------------------")
print(data_courant_1_10)
print(data_courant_10_20_10)
print(data_courant_15_9_1_10)

print("-----------------Debit eau-------------------------------")
print(data_Debit_eau_1_20_10)
print(data_Debit_eau_15_9_1_10)

print("-----------------Debit solide-------------------------------")
print(data_Debit_solide_1_20_10)
print(data_Debit_solide_15_9_1_10)

print("-----------------Refus tamis-------------------------------")
print(data_refus_tamis_octobre.head(10))
print(data_refus_tamis_septembre.head(10))

print("-----------------Puissance-------------------------------")
print(data_puissance_QA_1)
print(data_puissance_QA_2)
print(data_puissance_QA_3)
print(data_puissance_QA_4)
print(data_puissance_QA_5)
print(data_puissance_QA_6)
print(data_puissance_QA_7)

-----------------Courant-------------------------------
                COURANT Time    COURANT ValueY
0        01/10/2022 14:49:12  66,5901336669922
1        01/10/2022 14:49:12  63,8192291259766
2        01/10/2022 14:49:13  65,2097778320313
3        01/10/2022 14:49:13   59,011791229248
4        01/10/2022 14:49:14  67,0797119140625
...                      ...               ...
1559386  10/10/2022 15:49:09  63,9246215820313
1559387  10/10/2022 15:49:10  69,1196441650391
1559388  10/10/2022 15:49:10  62,0886840820313
1559389  10/10/2022 15:49:11  60,9837226867676
1559390  10/10/2022 15:49:11  60,3853454589844

[1559391 rows x 2 columns]
                COURANT Time    COURANT ValueY
0        10/10/2022 14:49:12  57,5158424377441
1        10/10/2022 14:49:12   60,963321685791
2        10/10/2022 14:49:13  55,4215126037598
3        10/10/2022 14:49:13  69,0856475830078
4        10/10/2022 14:49:14  55,5575103759766
...                      ...               ...
1734865  20/10/2022 15:49:09  57,8694305419922
1734866  20/10/2022 15:49:10  52,9939994812012
1734867  20/10/2022 15:49:10      60,677734375
1734868  20/10/2022 15:49:11  52,7254028320313
1734869  20/10/2022 15:49:11  59,7257690429688

[1734870 rows x 2 columns]
                COURANT Time    COURANT ValueY
0        15/09/2022 14:49:12  59,0287933349609
1        15/09/2022 14:49:12  60,0113563537598
2        15/09/2022 14:49:13      71,142578125
3        15/09/2022 14:49:13  70,0580139160156
4        15/09/2022 14:49:14  64,9411926269531
...                      ...               ...
2771995  01/10/2022 15:49:09  72,3563385009766
2771996  01/10/2022 15:49:10  64,0130157470703
2771997  01/10/2022 15:49:10  55,4623107910156
2771998  01/10/2022 15:49:11  58,7873992919922
2771999  01/10/2022 15:49:11  66,8009262084961

[2772000 rows x 2 columns]
-----------------Debit eau-------------------------------
             DEBIT EAU Time  DEBIT EAU ValueY
0       01/10/2022 14:45:20  13,2595481872559
1       01/10/2022 14:45:22  12,7893524169922
2       01/10/2022 14:45:24  12,4782991409302
3       01/10/2022 14:45:26  12,6265916824341
4       01/10/2022 14:45:28  12,5072345733643
...                     ...               ...
821980  20/10/2022 15:45:09             9,375
821981  20/10/2022 15:45:11  9,24840831756592
821982  20/10/2022 15:45:13  9,10011577606201
821983  20/10/2022 15:45:15  8,95182228088379
821984  20/10/2022 15:45:17  8,94097232818604

[821985 rows x 2 columns]
             DEBIT EAU Time  DEBIT EAU ValueY
0       15/09/2022 14:45:20  9,71137142181396
1       15/09/2022 14:45:22   10,076678276062
2       15/09/2022 14:45:24  10,3804979324341
3       15/09/2022 14:45:26  10,3370952606201
4       15/09/2022 14:45:28  10,1273145675659
...                     ...               ...
692995  01/10/2022 15:45:10   10,962818145752
692996  01/10/2022 15:45:12  10,9519672393799
692997  01/10/2022 15:45:14  10,7711229324341
692998  01/10/2022 15:45:16  10,4347515106201
692999  01/10/2022 15:45:18  10,3551797866821

[693000 rows x 2 columns]
-----------------Debit solide-------------------------------
                SOLIDE Time     SOLIDE ValueY
0       01/10/2022 14:40:58  144,504135131836
1       01/10/2022 14:41:00     146,728515625
2       01/10/2022 14:41:02  147,388595581055
3       01/10/2022 14:41:04   145,91471862793
4       01/10/2022 14:41:06  144,703048706055
...                     ...               ...
822152  20/10/2022 15:40:47  108,118125915527
822153  20/10/2022 15:40:49  107,828773498535
822154  20/10/2022 15:40:51  108,651626586914
822155  20/10/2022 15:40:53  108,190467834473
822156  20/10/2022 15:40:55  111,020690917969

[822157 rows x 2 columns]
                SOLIDE Time     SOLIDE ValueY
0       15/09/2022 14:40:58  115,134910583496
1       15/09/2022 14:41:00  114,447700500488
2       15/09/2022 14:41:02  115,297668457031
3       15/09/2022 14:41:04  115,315757751465
4       15/09/2022 14:41:06  115,315757751465
...                     ...               ...
692995  01/10/2022 15:40:48  113,905158996582
692996  01/10/2022 15:40:50  113,941337585449
692997  01/10/2022 15:40:52  114,447700500488
692998  01/10/2022 15:40:54  115,044486999512
692999  01/10/2022 15:40:56  114,637580871582

[693000 rows x 2 columns]
-----------------Refus tamis-------------------------------
                  Jours Poste Refus Tamis +500 en % QA
3   2022-10-01 00:00:00     1                22.182362
4   2022-10-01 00:00:00     2                19.904009
5   2022-10-01 00:00:00     3                      NaN
6   2022-10-02 00:00:00     1                      NaN
7   2022-10-02 00:00:00     2                      NaN
8   2022-10-02 00:00:00     3                      NaN
9   2022-10-03 00:00:00     1                14.732272
10  2022-10-03 00:00:00     2                24.994262
11  2022-10-03 00:00:00     3                16.490989
12  2022-10-04 00:00:00     1                34.245906
                  Jours Poste Refus Tamis +500 en % QA
3   2022-09-01 00:00:00     1                    29.03
4   2022-09-01 00:00:00     2                    22.29
5   2022-09-01 00:00:00     3                      NaN
6   2022-09-02 00:00:00     1                      NaN
7   2022-09-02 00:00:00     2                      NaN
8   2022-09-02 00:00:00     3                      NaN
9   2022-09-03 00:00:00     1                      NaN
10  2022-09-03 00:00:00     2                      NaN
11  2022-09-03 00:00:00     3                22.286924
12  2022-09-04 00:00:00     1                17.343463
-----------------Puissance-------------------------------
             PUISSANCE Time  PUISSANCE ValueY
0       15/09/2022 14:49:12   506,09228515625
1       15/09/2022 14:49:12  514,516418457031
2       15/09/2022 14:49:13  609,951599121094
3       15/09/2022 14:49:13  600,652954101563
4       15/09/2022 14:49:14    586,2822265625
...                     ...               ...
871195  20/09/2022 15:49:09  517,314819335938
871196  20/09/2022 15:49:10  571,212036132813
871197  20/09/2022 15:49:10  483,647155761719
871198  20/09/2022 15:49:11   647,20458984375
871199  20/09/2022 15:49:11  522,794860839844

[871200 rows x 2 columns]
             PUISSANCE Time  PUISSANCE ValueY
0       20/09/2022 16:01:56  512,330200195313
1       20/09/2022 16:01:56  567,014587402344
2       20/09/2022 16:01:57  526,292785644531
3       20/09/2022 16:01:57  541,013244628906
4       20/09/2022 16:01:58  541,013244628906
...                     ...               ...
871195  25/09/2022 17:01:53    573,1650390625
871196  25/09/2022 17:01:54  524,981140136719
871197  25/09/2022 17:01:54  524,981140136719
871198  25/09/2022 17:01:55    524,1357421875
871199  25/09/2022 17:01:55    524,1357421875

[871200 rows x 2 columns]
             PUISSANCE Time  PUISSANCE ValueY
0       25/09/2022 16:01:56  545,618896484375
1       25/09/2022 16:01:56  553,022888183594
2       25/09/2022 16:01:57   567,85986328125
3       25/09/2022 16:01:57   579,05322265625
4       25/09/2022 16:01:58  571,387023925781
...                     ...               ...
871195  30/09/2022 17:01:53  634,291381835938
871196  30/09/2022 17:01:54  562,088256835938
871197  30/09/2022 17:01:54  553,168640136719
871198  30/09/2022 17:01:55  519,530151367188
871199  30/09/2022 17:01:55  600,186584472656

[871200 rows x 2 columns]
             PUISSANCE Time  PUISSANCE ValueY
0       30/09/2022 16:01:56  670,786499023438
1       30/09/2022 16:01:56  468,168853759766
2       30/09/2022 16:01:57  468,343780517578
3       30/09/2022 16:01:57  591,354248046875
4       30/09/2022 16:01:58  548,154846191406
...                     ...               ...
868186  05/10/2022 17:01:53  519,384399414063
868187  05/10/2022 17:01:54  481,606719970703
868188  05/10/2022 17:01:54  537,457092285156
868189  05/10/2022 17:01:55  469,334808349609
868190  05/10/2022 17:01:55   590,45068359375

[868191 rows x 2 columns]
             PUISSANCE Time  PUISSANCE ValueY
0       05/10/2022 16:01:56  495,860809326172
1       05/10/2022 16:01:56  546,930541992188
2       05/10/2022 16:01:57  511,135101318359
3       05/10/2022 16:01:57  477,263488769531
4       05/10/2022 16:01:58     529,353515625
...                     ...               ...
871195  10/10/2022 17:01:53  521,220764160156
871196  10/10/2022 17:01:54  526,292785644531
871197  10/10/2022 17:01:54  487,757263183594
871198  10/10/2022 17:01:55  509,182067871094
871199  10/10/2022 17:01:55  454,293762207031

[871200 rows x 2 columns]
             PUISSANCE Time  PUISSANCE ValueY
0       10/10/2022 16:01:56  548,300598144531
1       10/10/2022 16:01:56  578,761779785156
2       10/10/2022 16:01:57  512,301086425781
3       10/10/2022 16:01:57  465,312225341797
4       10/10/2022 16:01:58  534,192321777344
...                     ...               ...
870865  15/10/2022 17:01:53  394,449981689453
870866  15/10/2022 17:01:54  524,922729492188
870867  15/10/2022 17:01:54  554,130554199219
870868  15/10/2022 17:01:55  518,947143554688
870869  15/10/2022 17:01:55  515,798950195313

[870870 rows x 2 columns]
             PUISSANCE Time  PUISSANCE ValueY
0       15/10/2022 16:01:56   576,16748046875
1       15/10/2022 16:01:56  542,937133789063
2       15/10/2022 16:01:57  433,801666259766
3       15/10/2022 16:01:57   538,12744140625
4       15/10/2022 16:01:58  483,676330566406
...                     ...               ...
871195  20/10/2022 17:01:53  557,774169921875
871196  20/10/2022 17:01:54  548,388061523438
871197  20/10/2022 17:01:54  456,509124755859
871198  20/10/2022 17:01:55  522,969787597656
871199  20/10/2022 17:01:55  554,655212402344

[871200 rows x 2 columns]

pre process refus tamis_octobre & septembre

In [40]:
process_refu_tamis(data_refus_tamis_octobre)
process_refu_tamis(data_refus_tamis_septembre)
print(data_refus_tamis_octobre)
print(data_refus_tamis_septembre)

                  Jours Poste Refus Tamis +500 en % QA
3   2022-10-01 00:00:00     1                22.182362
4   2022-10-01 00:00:00     2                19.904009
5   2022-10-01 00:00:00     3                      NaN
6   2022-10-02 00:00:00     1                      NaN
7   2022-10-02 00:00:00     2                      NaN
..                  ...   ...                      ...
94  2022-10-31 00:00:00     2                      NaN
95  2022-10-31 00:00:00     3                      NaN
96              MOYENNE   NaN                 20.71681
97              MOYENNE   NaN                12.694195
98              MOYENNE   NaN                34.245906

[96 rows x 3 columns]
                  Jours Poste Refus Tamis +500 en % QA
3   2022-09-01 00:00:00     1                    29.03
4   2022-09-01 00:00:00     2                    22.29
5   2022-09-01 00:00:00     3                      NaN
6   2022-09-02 00:00:00     1                      NaN
7   2022-09-02 00:00:00     2                      NaN
..                  ...   ...                      ...
91  2022-09-30 00:00:00     2                      NaN
92  2022-09-30 00:00:00     3                      NaN
93              MOYENNE   NaN                19.457157
94              MOYENNE   NaN                13.326848
95              MOYENNE   NaN                    29.03

[93 rows x 3 columns]

print the types of every column

In [42]:
print(data_courant_10_20_10.dtypes)
print(data_courant_1_10.dtypes)
print(data_courant_15_9_1_10.dtypes)

print(data_Debit_eau_1_20_10.dtypes)
print(data_Debit_eau_15_9_1_10.dtypes)

print(data_Debit_solide_1_20_10.dtypes)
print(data_Debit_solide_15_9_1_10.dtypes)

print(data_refus_tamis_octobre.dtypes)
print(data_refus_tamis_septembre.dtypes)

print(data_puissance_QA_1.dtypes)
print(data_puissance_QA_2.dtypes)
print(data_puissance_QA_3.dtypes)
print(data_puissance_QA_4.dtypes)
print(data_puissance_QA_5.dtypes)
print(data_puissance_QA_6.dtypes)
print(data_puissance_QA_7.dtypes)

COURANT Time      object
COURANT ValueY    object
dtype: object
COURANT Time      object
COURANT ValueY    object
dtype: object
COURANT Time      object
COURANT ValueY    object
dtype: object
DEBIT EAU Time      object
DEBIT EAU ValueY    object
dtype: object
DEBIT EAU Time      object
DEBIT EAU ValueY    object
dtype: object
SOLIDE Time      object
SOLIDE ValueY    object
dtype: object
SOLIDE Time      object
SOLIDE ValueY    object
dtype: object
Jours                       object
Poste                       object
Refus Tamis +500 en % QA    object
dtype: object
Jours                       object
Poste                       object
Refus Tamis +500 en % QA    object
dtype: object
PUISSANCE Time      object
PUISSANCE ValueY    object
dtype: object
PUISSANCE Time      object
PUISSANCE ValueY    object
dtype: object
PUISSANCE Time      object
PUISSANCE ValueY    object
dtype: object
PUISSANCE Time      object
PUISSANCE ValueY    object
dtype: object
PUISSANCE Time      object
PUISSANCE ValueY    object
dtype: object
PUISSANCE Time      object
PUISSANCE ValueY    object
dtype: object
PUISSANCE Time      object
PUISSANCE ValueY    object
dtype: object

In [61]:
frames = (data_courant_15_9_1_10 , data_courant_1_10 , data_courant_10_20_10)
data_courant_15_9_a_20_10 = pd.concat(frames)
data_courant_15_9_a_20_10

                COURANT Time    COURANT ValueY
0        15/09/2022 14:49:12  59,0287933349609
1        15/09/2022 14:49:12  60,0113563537598
2        15/09/2022 14:49:13      71,142578125
3        15/09/2022 14:49:13  70,0580139160156
4        15/09/2022 14:49:14  64,9411926269531
...                      ...               ...
1734865  20/10/2022 15:49:09  57,8694305419922
1734866  20/10/2022 15:49:10  52,9939994812012
1734867  20/10/2022 15:49:10      60,677734375
1734868  20/10/2022 15:49:11  52,7254028320313
1734869  20/10/2022 15:49:11  59,7257690429688

[6066261 rows x 2 columns]

In [62]:
frames_2 = (data_Debit_eau_15_9_1_10 , data_Debit_eau_1_20_10)
data_debit_eau_15_9_a_20_10 = pd.concat(frames_2)
data_debit_eau_15_9_a_20_10

             DEBIT EAU Time  DEBIT EAU ValueY
0       15/09/2022 14:45:20  9,71137142181396
1       15/09/2022 14:45:22   10,076678276062
2       15/09/2022 14:45:24  10,3804979324341
3       15/09/2022 14:45:26  10,3370952606201
4       15/09/2022 14:45:28  10,1273145675659
...                     ...               ...
821980  20/10/2022 15:45:09             9,375
821981  20/10/2022 15:45:11  9,24840831756592
821982  20/10/2022 15:45:13  9,10011577606201
821983  20/10/2022 15:45:15  8,95182228088379
821984  20/10/2022 15:45:17  8,94097232818604

[1514985 rows x 2 columns]

In [63]:
frames_3 = (data_Debit_solide_15_9_1_10 , data_Debit_solide_1_20_10)
data_debit_solide_15_9_a_20_10 = pd.concat(frames_3)
data_debit_solide_15_9_a_20_10

                SOLIDE Time     SOLIDE ValueY
0       15/09/2022 14:40:58  115,134910583496
1       15/09/2022 14:41:00  114,447700500488
2       15/09/2022 14:41:02  115,297668457031
3       15/09/2022 14:41:04  115,315757751465
4       15/09/2022 14:41:06  115,315757751465
...                     ...               ...
822152  20/10/2022 15:40:47  108,118125915527
822153  20/10/2022 15:40:49  107,828773498535
822154  20/10/2022 15:40:51  108,651626586914
822155  20/10/2022 15:40:53  108,190467834473
822156  20/10/2022 15:40:55  111,020690917969

[1515157 rows x 2 columns]

In [64]:
frames_4 = (data_refus_tamis_octobre , data_refus_tamis_septembre)
data_refus_tamis_15_9_a_20_10 = pd.concat(frames_4)
data_refus_tamis_15_9_a_20_10

                  Jours Poste Refus Tamis +500 en % QA
3   2022-10-01 00:00:00     1                22.182362
4   2022-10-01 00:00:00     2                19.904009
5   2022-10-01 00:00:00     3                      NaN
6   2022-10-02 00:00:00     1                      NaN
7   2022-10-02 00:00:00     2                      NaN
..                  ...   ...                      ...
91  2022-09-30 00:00:00     2                      NaN
92  2022-09-30 00:00:00     3                      NaN
93              MOYENNE   NaN                19.457157
94              MOYENNE   NaN                13.326848
95              MOYENNE   NaN                    29.03

[189 rows x 3 columns]

In [65]:
frames_5 = (data_puissance_QA_1,data_puissance_QA_2,data_puissance_QA_3,data_puissance_QA_4,data_puissance_QA_5,data_puissance_QA_6,data_puissance_QA_7)
data_puissance_15_9_a_20_10 = pd.concat(frames_5)
data_puissance_15_9_a_20_10

             PUISSANCE Time  PUISSANCE ValueY
0       15/09/2022 14:49:12   506,09228515625
1       15/09/2022 14:49:12  514,516418457031
2       15/09/2022 14:49:13  609,951599121094
3       15/09/2022 14:49:13  600,652954101563
4       15/09/2022 14:49:14    586,2822265625
...                     ...               ...
871195  20/10/2022 17:01:53  557,774169921875
871196  20/10/2022 17:01:54  548,388061523438
871197  20/10/2022 17:01:54  456,509124755859
871198  20/10/2022 17:01:55  522,969787597656
871199  20/10/2022 17:01:55  554,655212402344

[6095061 rows x 2 columns]

Convert the types from object to date_time

In [66]:
data_courant_15_9_a_20_10['COURANT Time'] = pd.to_datetime(data_courant_15_9_a_20_10['COURANT Time'], format="%d/%m/%Y %H:%M:%S")
data_debit_eau_15_9_a_20_10['DEBIT EAU Time'] = pd.to_datetime(data_debit_eau_15_9_a_20_10['DEBIT EAU Time'], format="%d/%m/%Y %H:%M:%S")
data_debit_solide_15_9_a_20_10['SOLIDE Time'] = pd.to_datetime(data_debit_solide_15_9_a_20_10['SOLIDE Time'], format="%d/%m/%Y %H:%M:%S")
data_puissance_15_9_a_20_10['PUISSANCE Time'] = pd.to_datetime(data_puissance_15_9_a_20_10['PUISSANCE Time'], format="%d/%m/%Y %H:%M:%S")
#data_refus_tamis_15_9_a_20_10['Jours'] = pd.to_datetime(data_refus_tamis_15_9_a_20_10['Jours'], format="%Y/%m/%d %H:%M:%S")

In [67]:
print(data_courant_15_9_a_20_10.dtypes)
print(data_debit_eau_15_9_a_20_10.dtypes)
print(data_debit_solide_15_9_a_20_10.dtypes)
print(data_puissance_15_9_a_20_10.dtypes)
#print(data_refus_tamis_15_9_a_20_10.dtypes)

COURANT Time      datetime64[ns]
COURANT ValueY            object
dtype: object
DEBIT EAU Time      datetime64[ns]
DEBIT EAU ValueY            object
dtype: object
SOLIDE Time      datetime64[ns]
SOLIDE ValueY            object
dtype: object
PUISSANCE Time      datetime64[ns]
PUISSANCE ValueY            object
dtype: object

Replace the "," by "."

In [68]:
data_courant_15_9_a_20_10["COURANT ValueY"] = data_courant_15_9_a_20_10["COURANT ValueY"].apply(lambda x: x.replace("," , "."))
data_debit_eau_15_9_a_20_10["DEBIT EAU ValueY"] = data_debit_eau_15_9_a_20_10["DEBIT EAU ValueY"].apply(lambda x: x.replace("," , "."))
data_debit_solide_15_9_a_20_10["SOLIDE ValueY"] = data_debit_solide_15_9_a_20_10["SOLIDE ValueY"].apply(lambda x: x.replace("," , "."))
data_puissance_15_9_a_20_10["PUISSANCE ValueY"] = data_puissance_15_9_a_20_10["PUISSANCE ValueY"].apply(lambda x: x.replace("," , "."))

Change the type from "object" to "float" for the Value Columns

In [69]:
data_courant_15_9_a_20_10["COURANT ValueY"] = data_courant_15_9_a_20_10["COURANT ValueY"].astype(float)
data_debit_eau_15_9_a_20_10["DEBIT EAU ValueY"] = data_debit_eau_15_9_a_20_10["DEBIT EAU ValueY"].astype(float)
data_debit_solide_15_9_a_20_10["SOLIDE ValueY"] = data_debit_solide_15_9_a_20_10["SOLIDE ValueY"].astype(float)
data_puissance_15_9_a_20_10["PUISSANCE ValueY"] = data_puissance_15_9_a_20_10["PUISSANCE ValueY"].astype(float)

Shape of every csv file

In [70]:
print(data_courant_15_9_a_20_10.shape)
print(data_debit_eau_15_9_a_20_10.shape)
print(data_debit_solide_15_9_a_20_10.shape)
print(data_refus_tamis_15_9_a_20_10.shape)
print(data_puissance_15_9_a_20_10.shape)

(6066261, 2)
(1514985, 2)
(1515157, 2)
(189, 3)
(6095061, 2)

The max and the min

In [71]:
print("Courant : ")
print(data_courant_15_9_a_20_10['COURANT Time'].min())
print(data_courant_15_9_a_20_10['COURANT Time'].max())
print("Débit Eau")
print(data_debit_eau_15_9_a_20_10['DEBIT EAU Time'].min())
print(data_debit_eau_15_9_a_20_10['DEBIT EAU Time'].max())
print("Débit Solide")
print(data_debit_solide_15_9_a_20_10['SOLIDE Time'].min())
print(data_debit_solide_15_9_a_20_10['SOLIDE Time'].max())
print("Puissance")
print(data_puissance_15_9_a_20_10['PUISSANCE Time'].min())
print(data_puissance_15_9_a_20_10['PUISSANCE Time'].max())

Courant :
2022-09-15 14:49:12
2022-10-20 15:49:11
Débit Eau
2022-09-15 14:45:20
2022-10-20 15:45:17
Débit Solide
2022-09-15 14:40:58
2022-10-20 15:40:55
Puissance
2022-09-15 14:49:12
2022-10-20 17:01:55

In [76]:
def second_to_minute_2(data):
    columns = data.columns
    time_start = pd.to_datetime("2022-09-15 14:40:00")
    time_end = pd.to_datetime("2022-10-20 17:01:00")
    list_time = []
    list_value = []
    list_value_2 = []
    while(time_start <= time_end):
        interv = data[data[columns[0]].between(time_start,time_start + timedelta(minutes=1))]
        if interv.shape[0] == 0:
            list_value.append(float("nan"))
        else:
            list_value.append(interv[columns[1]].mean())
        list_time.append(time_start)
        if len(columns) == 4:
            list_value_2.append(interv[columns[3]].mean())
        time_start = time_start + timedelta(minutes=1)
    if len(columns) == 2:
        new_data = pd.DataFrame(data=zip(list_time,list_value),columns=[columns[0],columns[1]])
    elif len(columns) == 4:
        new_data = pd.DataFrame(data=zip(list_time,list_value,list_value_2),columns=[columns[0],columns[1],columns[3]])
    return new_data

In [77]:
new_data_courant_15_9_a_20_10 = second_to_minute_2(data_courant_15_9_a_20_10)
new_data_debit_eau_15_9_a_20_10 = second_to_minute_2(data_debit_eau_15_9_a_20_10)
new_data_debit_solide_15_9_a_20_10 = second_to_minute_2(data_debit_solide_15_9_a_20_10)
new_data_puissance_15_9_a_20_10 = second_to_minute_2(data_puissance_15_9_a_20_10)

In [80]:
print(new_data_courant_15_9_a_20_10)
print(new_data_debit_eau_15_9_a_20_10)
print(new_data_debit_solide_15_9_a_20_10)
print(new_data_puissance_15_9_a_20_10)

             COURANT Time  COURANT ValueY
0     2022-09-15 14:40:00             NaN
1     2022-09-15 14:41:00             NaN
2     2022-09-15 14:42:00             NaN
3     2022-09-15 14:43:00             NaN
4     2022-09-15 14:44:00             NaN
...                   ...             ...
50537 2022-10-20 16:57:00             NaN
50538 2022-10-20 16:58:00             NaN
50539 2022-10-20 16:59:00             NaN
50540 2022-10-20 17:00:00             NaN
50541 2022-10-20 17:01:00             NaN

[50542 rows x 2 columns]
           DEBIT EAU Time  DEBIT EAU ValueY
0     2022-09-15 14:40:00               NaN
1     2022-09-15 14:41:00               NaN
2     2022-09-15 14:42:00               NaN
3     2022-09-15 14:43:00               NaN
4     2022-09-15 14:44:00               NaN
...                   ...               ...
50537 2022-10-20 16:57:00               NaN
50538 2022-10-20 16:58:00               NaN
50539 2022-10-20 16:59:00               NaN
50540 2022-10-20 17:00:00               NaN
50541 2022-10-20 17:01:00               NaN

[50542 rows x 2 columns]
              SOLIDE Time  SOLIDE ValueY
0     2022-09-15 14:40:00     114.791306
1     2022-09-15 14:41:00     116.841270
2     2022-09-15 14:42:00     114.797431
3     2022-09-15 14:43:00     114.255771
4     2022-09-15 14:44:00     117.610444
...                   ...            ...
50537 2022-10-20 16:57:00            NaN
50538 2022-10-20 16:58:00            NaN
50539 2022-10-20 16:59:00            NaN
50540 2022-10-20 17:00:00            NaN
50541 2022-10-20 17:01:00            NaN

[50542 rows x 2 columns]
           PUISSANCE Time  PUISSANCE ValueY
0     2022-09-15 14:40:00               NaN
1     2022-09-15 14:41:00               NaN
2     2022-09-15 14:42:00               NaN
3     2022-09-15 14:43:00               NaN
4     2022-09-15 14:44:00               NaN
...                   ...               ...
50537 2022-10-20 16:57:00        507.211636
50538 2022-10-20 16:58:00        511.160186
50539 2022-10-20 16:59:00        509.005283
50540 2022-10-20 17:00:00        510.360491
50541 2022-10-20 17:01:00        509.105051

[50542 rows x 2 columns]

In [83]:
new_data_courant_15_9_a_20_10["COURANT ValueY"].isna().sum()
new_data_courant_15_9_a_20_10.head(50)

          COURANT Time  COURANT ValueY
0  2022-09-15 14:40:00             NaN
1  2022-09-15 14:41:00             NaN
2  2022-09-15 14:42:00             NaN
3  2022-09-15 14:43:00             NaN
4  2022-09-15 14:44:00             NaN
5  2022-09-15 14:45:00             NaN
6  2022-09-15 14:46:00             NaN
7  2022-09-15 14:47:00             NaN
8  2022-09-15 14:48:00             NaN
9  2022-09-15 14:49:00       66.659241
10 2022-09-15 14:50:00       66.816950
11 2022-09-15 14:51:00       66.735882
12 2022-09-15 14:52:00       66.915797
13 2022-09-15 14:53:00       67.326347
14 2022-09-15 14:54:00       67.764821
15 2022-09-15 14:55:00       67.349924
16 2022-09-15 14:56:00       66.864967
17 2022-09-15 14:57:00       66.161385
18 2022-09-15 14:58:00       66.018061
19 2022-09-15 14:59:00       67.038193
20 2022-09-15 15:00:00       66.202631
21 2022-09-15 15:01:00       66.860424
22 2022-09-15 15:02:00       66.131092
23 2022-09-15 15:03:00       66.183596
24 2022-09-15 15:04:00       65.917959
25 2022-09-15 15:05:00       65.362691
26 2022-09-15 15:06:00       65.311108
27 2022-09-15 15:07:00       65.350625
28 2022-09-15 15:08:00       64.983910
29 2022-09-15 15:09:00       66.337260
30 2022-09-15 15:10:00       64.534513
31 2022-09-15 15:11:00       64.596631
32 2022-09-15 15:12:00       65.667232
33 2022-09-15 15:13:00       64.900446
34 2022-09-15 15:14:00       65.039730
35 2022-09-15 15:15:00       65.638723
36 2022-09-15 15:16:00       65.493698
37 2022-09-15 15:17:00       66.085863
38 2022-09-15 15:18:00       65.047255
39 2022-09-15 15:19:00       65.160398
40 2022-09-15 15:20:00       65.796204
41 2022-09-15 15:21:00       65.129437
42 2022-09-15 15:22:00       65.906060
43 2022-09-15 15:23:00       66.406149
44 2022-09-15 15:24:00       65.221540
45 2022-09-15 15:25:00       66.057020
46 2022-09-15 15:26:00       65.629610
47 2022-09-15 15:27:00       65.945994
48 2022-09-15 15:28:00       65.550326
49 2022-09-15 15:29:00       65.913779

In [84]:
new_data_courant_15_9_a_20_10.rename(columns={"COURANT Time": "Time"}, inplace=True)
new_data_debit_eau_15_9_a_20_10.rename(columns={"DEBIT EAU Time": "Time"}, inplace=True)
new_data_debit_solide_15_9_a_20_10.rename(columns={"SOLIDE Time": "Time"}, inplace=True)
new_data_puissance_15_9_a_20_10.rename(columns={"PUISSANCE Time": "Time"}, inplace=True)

In [85]:
data_15_09_a_20_10 = pd.merge(pd.merge(new_data_courant_15_9_a_20_10,new_data_debit_eau_15_9_a_20_10,on='Time'),pd.merge(new_data_debit_solide_15_9_a_20_10,new_data_puissance_15_9_a_20_10,on='Time'),on="Time")

In [86]:
data_15_09_a_20_10

,Time,COURANT ValueY,DEBIT EAU ValueY,SOLIDE ValueY,PUISSANCE ValueY
0,2022-09-15 14:40:00,NaN,NaN,114.791306,NaN
1,2022-09-15 14:41:00,NaN,NaN,116.841270,NaN
2,2022-09-15 14:42:00,NaN,NaN,114.797431,NaN
3,2022-09-15 14:43:00,NaN,NaN,114.255771,NaN
4,2022-09-15 14:44:00,NaN,NaN,117.610444,NaN
...,...,...,...,...,...
50537,2022-10-20 16:57:00,NaN,NaN,NaN,507.211636
50538,2022-10-20 16:58:00,NaN,NaN,NaN,511.160186
50539,2022-10-20 16:59:00,NaN,NaN,NaN,509.005283
50540,2022-10-20 17:00:00,NaN,NaN,NaN,510.360491
50541,2022-10-20 17:01:00,NaN,NaN,NaN,509.105051

In [ ]:
data_15_09_a_20_10.to_csv("data_15_09_a_20_10.csv")

23_08 --> 15_09

Read csv files

In [3]:
data_courant_23_27_8 = pd.read_csv("De 23_08 à 15_09 2022\Courant\COURANT QA 23  27   8.csv", encoding='utf-16',sep="\t") 
data_courant_27_31_8 = pd.read_csv("De 23_08 à 15_09 2022\Courant\COURANT QA 27  31   8.csv", encoding='utf-16',sep="\t") 
data_courant_31_8_10_9 = pd.read_csv("De 23_08 à 15_09 2022\Courant\COURANT QA 31  8  10 9.csv", encoding='utf-16',sep="\t") 
data_courant_10_15_9 = pd.read_csv("De 23_08 à 15_09 2022\Courant\COURANT QA 10 15    9.csv", encoding='utf-16',sep="\t") 


data_Debit_eau_23_8_15_9 = pd.read_csv("De 23_08 à 15_09 2022\Débit Eau\DEBIT EAU ENTREE QA 23  8  15 9.csv",encoding='utf-16',sep="\t") 

data_Debit_solide_23_8_15_9 = pd.read_csv("De 23_08 à 15_09 2022\Débit Solide\DEBIT SOLIDE ENTREE QA 23  8 15 9.csv",encoding='utf-16', sep= '\t') 

data_refus_tamis_aout = pd.read_excel("De 23_08 à 15_09 2022\Refus Tamis\TB_D80_et_performances_Usine_Août_2022.xlsx")
data_refus_tamis_septembre_2 = pd.read_excel("De 23_08 à 15_09 2022\Refus Tamis\TB_D80_et_performances_Usine_Septembre_2022.xlsx")

data_puissance_QA_23_8_1_9 = pd.read_csv("De 23_08 à 15_09 2022\Puissance\PUISSACE    QA 23 8 1 9.csv",encoding='utf-16',sep="\t") 
data_puissance_QA_1_15_9 = pd.read_csv("De 23_08 à 15_09 2022\Puissance\PUISSANCE QA  1 15 9.csv",encoding='utf-16',sep="\t")

In [4]:
print("-----------------Courant-------------------------------")
print(data_courant_23_27_8)
print(data_courant_27_31_8)
print(data_courant_31_8_10_9)
print(data_courant_10_15_9)

print("-----------------Debit eau-------------------------------")
print(data_Debit_eau_23_8_15_9)


print("-----------------Debit solide-------------------------------")
print(data_Debit_solide_23_8_15_9)


print("-----------------Refus tamis-------------------------------")
print(data_refus_tamis_aout.head(10))
print(data_refus_tamis_septembre_2.head(10))

print("-----------------Puissance-------------------------------")
print(data_puissance_QA_23_8_1_9)
print(data_puissance_QA_1_15_9)

-----------------Courant-------------------------------
               COURANT Time    COURANT ValueY
0       23/08/2022 14:50:42  72,2747344970703
1       23/08/2022 14:50:42  71,5607604980469
2       23/08/2022 14:50:43  73,4544982910156
3       23/08/2022 14:50:43  66,8927230834961
4       23/08/2022 14:50:44  66,4031372070313
...                     ...               ...
619109  27/08/2022 04:50:39  63,5982360839844
619110  27/08/2022 04:50:40  64,2408142089844
619111  27/08/2022 04:50:40  64,2408142089844
619112  27/08/2022 04:50:41  71,6389617919922
619113  27/08/2022 04:50:41   63,258243560791

[619114 rows x 2 columns]
               COURANT Time    COURANT ValueY
0       27/08/2022 04:50:42  74,6886596679688
1       27/08/2022 04:50:42  74,6444549560547
2       27/08/2022 04:50:43  61,1979179382324
3       27/08/2022 04:50:43  68,0010833740234
4       27/08/2022 04:50:44  65,2097778320313
...                     ...               ...
691195  31/08/2022 04:50:39  66,6071319580078
691196  31/08/2022 04:50:40  70,5509948730469
691197  31/08/2022 04:50:40  74,5866622924805
691198  31/08/2022 04:50:41  69,1570434570313
691199  31/08/2022 04:50:41  64,9819869995117

[691200 rows x 2 columns]
                COURANT Time    COURANT ValueY
0        31/08/2022 04:50:42      69,306640625
1        31/08/2022 04:50:42  74,1854705810547
2        31/08/2022 04:50:43  70,2926025390625
3        31/08/2022 04:50:43  69,9356231689453
4        31/08/2022 04:50:44  67,6338958740234
...                      ...               ...
1727995  10/09/2022 04:50:39  67,6168975830078
1727996  10/09/2022 04:50:40  63,4248390197754
1727997  10/09/2022 04:50:40   63,054256439209
1727998  10/09/2022 04:50:41  65,6075668334961
1727999  10/09/2022 04:50:41  71,0235824584961

[1728000 rows x 2 columns]
               COURANT Time    COURANT ValueY
0       10/09/2022 04:50:42  77,7145538330078
1       10/09/2022 04:50:42  56,7338714599609
2       10/09/2022 04:50:43  60,1507530212402
3       10/09/2022 04:50:43  56,6454734802246
4       10/09/2022 04:50:44  56,5298767089844
...                     ...               ...
863995  15/09/2022 04:50:39   59,402774810791
863996  15/09/2022 04:50:40  63,2038459777832
863997  15/09/2022 04:50:40  66,0291519165039
863998  15/09/2022 04:50:41  66,6887283325195
863999  15/09/2022 04:50:41  54,6531372070313

[864000 rows x 2 columns]
-----------------Debit eau-------------------------------
             DEBIT EAU Time  DEBIT EAU ValueY
0       23/08/2022 17:02:30  12,4421300888062
1       23/08/2022 17:02:32  12,6880779266357
2       23/08/2022 17:02:34  12,6844615936279
3       23/08/2022 17:02:36   12,720630645752
4       23/08/2022 17:02:38  12,6844615936279
...                     ...               ...
995395  15/09/2022 18:02:20   10,474536895752
995396  15/09/2022 18:02:22  10,4419851303101
995397  15/09/2022 18:02:24  10,9049472808838
995398  15/09/2022 18:02:26  11,2883386611938
995399  15/09/2022 18:02:28  11,4908847808838

[995400 rows x 2 columns]
-----------------Debit solide-------------------------------
                SOLIDE Time     SOLIDE ValueY          SP_INT Time  \
0       23/08/2022 17:01:18  113,624855041504  23/08/2022 17:01:18
1       23/08/2022 17:01:20  114,438659667969  23/08/2022 17:01:20
2       23/08/2022 17:01:22  114,565246582031  23/08/2022 17:01:22
3       23/08/2022 17:01:24  113,778579711914  23/08/2022 17:01:24
4       23/08/2022 17:01:26  113,642936706543  23/08/2022 17:01:26
...                     ...               ...                  ...
995395  15/09/2022 18:01:08  115,939666748047  15/09/2022 18:01:08
995396  15/09/2022 18:01:10  116,970489501953  15/09/2022 18:01:10
995397  15/09/2022 18:01:12  116,717300415039  15/09/2022 18:01:12
995398  15/09/2022 18:01:14  118,697555541992  15/09/2022 18:01:14
995399  15/09/2022 18:01:16  120,506004333496  15/09/2022 18:01:16

        SP_INT ValueY
0                 115
1                 115
2                 115
3                 115
4                 115
...               ...
995395            115
995396            115
995397            115
995398            115
995399            115

[995400 rows x 4 columns]
-----------------Refus tamis-------------------------------
   Unnamed: 0           Unnamed: 1 Unnamed: 2                Unnamed: 3
0         NaN                  NaN        NaN                       NaN
1         NaN                Jours      Poste  Refus Tamis +500 en % QA
2         NaN                  NaN        NaN                       NaN
3         NaN  2022-08-01 00:00:00          1                 15.829722
4         NaN                  NaN          2                 21.457873
5         NaN                  NaN          3                 23.030496
6         NaN  2022-08-02 00:00:00          1                 19.087793
7         NaN                  NaN          2                 18.954439
8         NaN                  NaN          3                 23.087339
9         NaN  2022-08-03 00:00:00          1                 16.993132
   Unnamed: 0           Unnamed: 1 Unnamed: 2                Unnamed: 3
0         NaN                  NaN        NaN                       NaN
1         NaN                Jours      Poste  Refus Tamis +500 en % QA
2         NaN                  NaN        NaN                       NaN
3         NaN  2022-09-01 00:00:00          1                     29.03
4         NaN                  NaN          2                     22.29
5         NaN                  NaN          3                       NaN
6         NaN  2022-09-02 00:00:00          1                       NaN
7         NaN                  NaN          2                       NaN
8         NaN                  NaN          3                       NaN
9         NaN  2022-09-03 00:00:00          1                       NaN
-----------------Puissance-------------------------------
              PUISSANCE Time  PUISSANCE ValueY
0        23/08/2022 13:46:49  600,419738769531
1        23/08/2022 13:46:49  600,419738769531
2        23/08/2022 13:46:50  558,736083984375
3        23/08/2022 13:46:50  609,368713378906
4        23/08/2022 13:46:51  641,462158203125
...                      ...               ...
1490775  01/09/2022 04:50:39  619,075378417969
1490776  01/09/2022 04:50:40  634,466247558594
1490777  01/09/2022 04:50:40  614,323974609375
1490778  01/09/2022 04:50:41  558,940124511719
1490779  01/09/2022 04:50:41     601,935546875

[1490780 rows x 2 columns]
              PUISSANCE Time  PUISSANCE ValueY
0        01/09/2022 04:50:42  640,296142578125
1        01/09/2022 04:50:42  493,208251953125
2        01/09/2022 04:50:43  486,445556640625
3        01/09/2022 04:50:43  691,861572265625
4        01/09/2022 04:50:44  565,731994628906
...                      ...               ...
2419195  15/09/2022 04:50:39  509,298645019531
2419196  15/09/2022 04:50:40  515,857299804688
2419197  15/09/2022 04:50:40  566,110961914063
2419198  15/09/2022 04:50:41  571,765869140625
2419199  15/09/2022 04:50:41  468,576904296875

[2419200 rows x 2 columns]

pre process refus tamis_aout & septembre_2

In [5]:
process_refu_tamis(data_refus_tamis_aout)
process_refu_tamis(data_refus_tamis_septembre_2)
print(data_refus_tamis_aout)
print(data_refus_tamis_septembre_2)

                  Jours Poste Refus Tamis +500 en % QA
3   2022-08-01 00:00:00     1                15.829722
4   2022-08-01 00:00:00     2                21.457873
5   2022-08-01 00:00:00     3                23.030496
6   2022-08-02 00:00:00     1                19.087793
7   2022-08-02 00:00:00     2                18.954439
..                  ...   ...                      ...
94  2022-08-31 00:00:00     2                19.498698
95  2022-08-31 00:00:00     3                 18.86958
96              MOYENNE   NaN                19.600263
97              MOYENNE   NaN                13.544802
98              MOYENNE   NaN                29.775759

[96 rows x 3 columns]
                  Jours Poste Refus Tamis +500 en % QA
3   2022-09-01 00:00:00     1                    29.03
4   2022-09-01 00:00:00     2                    22.29
5   2022-09-01 00:00:00     3                      NaN
6   2022-09-02 00:00:00     1                      NaN
7   2022-09-02 00:00:00     2                      NaN
..                  ...   ...                      ...
91  2022-09-30 00:00:00     2                      NaN
92  2022-09-30 00:00:00     3                      NaN
93              MOYENNE   NaN                19.457157
94              MOYENNE   NaN                13.326848
95              MOYENNE   NaN                    29.03

[93 rows x 3 columns]

print the types of every column

In [6]:
print(data_courant_23_27_8.dtypes)
print(data_courant_27_31_8.dtypes)
print(data_courant_31_8_10_9.dtypes)
print(data_courant_10_15_9.dtypes)

print(data_Debit_eau_23_8_15_9.dtypes)


print(data_Debit_solide_23_8_15_9.dtypes)


print(data_refus_tamis_aout.dtypes)
print(data_refus_tamis_septembre_2.dtypes)

print(data_puissance_QA_23_8_1_9.dtypes)
print(data_puissance_QA_1_15_9.dtypes)

COURANT Time      object
COURANT ValueY    object
dtype: object
COURANT Time      object
COURANT ValueY    object
dtype: object
COURANT Time      object
COURANT ValueY    object
dtype: object
COURANT Time      object
COURANT ValueY    object
dtype: object
DEBIT EAU Time      object
DEBIT EAU ValueY    object
dtype: object
SOLIDE Time      object
SOLIDE ValueY    object
SP_INT Time      object
SP_INT ValueY     int64
dtype: object
Jours                       object
Poste                       object
Refus Tamis +500 en % QA    object
dtype: object
Jours                       object
Poste                       object
Refus Tamis +500 en % QA    object
dtype: object
PUISSANCE Time      object
PUISSANCE ValueY    object
dtype: object
PUISSANCE Time      object
PUISSANCE ValueY    object
dtype: object

In [7]:
frames = (data_courant_23_27_8 , data_courant_27_31_8 , data_courant_31_8_10_9, data_courant_10_15_9)
data_courant_23_8_a_15_9 = pd.concat(frames)
data_courant_23_8_a_15_9

               COURANT Time    COURANT ValueY
0       23/08/2022 14:50:42  72,2747344970703
1       23/08/2022 14:50:42  71,5607604980469
2       23/08/2022 14:50:43  73,4544982910156
3       23/08/2022 14:50:43  66,8927230834961
4       23/08/2022 14:50:44  66,4031372070313
...                     ...               ...
863995  15/09/2022 04:50:39   59,402774810791
863996  15/09/2022 04:50:40  63,2038459777832
863997  15/09/2022 04:50:40  66,0291519165039
863998  15/09/2022 04:50:41  66,6887283325195
863999  15/09/2022 04:50:41  54,6531372070313

[3902314 rows x 2 columns]

In [8]:
frames_2 = (data_refus_tamis_aout , data_refus_tamis_septembre_2)
data_refus_tamis_23_8_a_15_9 = pd.concat(frames_2)
data_refus_tamis_23_8_a_15_9

                  Jours Poste Refus Tamis +500 en % QA
3   2022-08-01 00:00:00     1                15.829722
4   2022-08-01 00:00:00     2                21.457873
5   2022-08-01 00:00:00     3                23.030496
6   2022-08-02 00:00:00     1                19.087793
7   2022-08-02 00:00:00     2                18.954439
..                  ...   ...                      ...
91  2022-09-30 00:00:00     2                      NaN
92  2022-09-30 00:00:00     3                      NaN
93              MOYENNE   NaN                19.457157
94              MOYENNE   NaN                13.326848
95              MOYENNE   NaN                    29.03

[189 rows x 3 columns]

In [9]:
frames_3 = (data_puissance_QA_23_8_1_9 , data_puissance_QA_1_15_9)
data_puissance_23_8_a_15_9 = pd.concat(frames_3)
data_puissance_23_8_a_15_9

              PUISSANCE Time  PUISSANCE ValueY
0        23/08/2022 13:46:49  600,419738769531
1        23/08/2022 13:46:49  600,419738769531
2        23/08/2022 13:46:50  558,736083984375
3        23/08/2022 13:46:50  609,368713378906
4        23/08/2022 13:46:51  641,462158203125
...                      ...               ...
2419195  15/09/2022 04:50:39  509,298645019531
2419196  15/09/2022 04:50:40  515,857299804688
2419197  15/09/2022 04:50:40  566,110961914063
2419198  15/09/2022 04:50:41  571,765869140625
2419199  15/09/2022 04:50:41  468,576904296875

[3909980 rows x 2 columns]

Convert the types from object to date_time

In [10]:
data_courant_23_8_a_15_9['COURANT Time'] = pd.to_datetime(data_courant_23_8_a_15_9['COURANT Time'], format="%d/%m/%Y %H:%M:%S")
data_Debit_eau_23_8_15_9['DEBIT EAU Time'] = pd.to_datetime(data_Debit_eau_23_8_15_9['DEBIT EAU Time'], format="%d/%m/%Y %H:%M:%S")
data_Debit_solide_23_8_15_9['SOLIDE Time'] = pd.to_datetime(data_Debit_solide_23_8_15_9['SOLIDE Time'], format="%d/%m/%Y %H:%M:%S")
data_puissance_23_8_a_15_9['PUISSANCE Time'] = pd.to_datetime(data_puissance_23_8_a_15_9['PUISSANCE Time'], format="%d/%m/%Y %H:%M:%S")
#data_refus_tamis_23_8_a_15_9['Jours'] = pd.to_datetime(data_refus_tamis_23_8_a_15_9['Jours'], format="%Y/%m/%d %H:%M:%S")

In [11]:
print(data_courant_23_8_a_15_9.dtypes)
print(data_Debit_eau_23_8_15_9.dtypes)
print(data_Debit_solide_23_8_15_9.dtypes)
print(data_puissance_23_8_a_15_9.dtypes)
#print(data_refus_tamis_23_8_a_15_9.dtypes)

COURANT Time      datetime64[ns]
COURANT ValueY            object
dtype: object
DEBIT EAU Time      datetime64[ns]
DEBIT EAU ValueY            object
dtype: object
SOLIDE Time      datetime64[ns]
SOLIDE ValueY            object
SP_INT Time              object
SP_INT ValueY             int64
dtype: object
PUISSANCE Time      datetime64[ns]
PUISSANCE ValueY            object
dtype: object

Replace the "," by "."

In [12]:
data_courant_23_8_a_15_9["COURANT ValueY"] = data_courant_23_8_a_15_9["COURANT ValueY"].apply(lambda x: x.replace("," , "."))
data_Debit_eau_23_8_15_9["DEBIT EAU ValueY"] = data_Debit_eau_23_8_15_9["DEBIT EAU ValueY"].apply(lambda x: x.replace("," , "."))
data_Debit_solide_23_8_15_9["SOLIDE ValueY"] = data_Debit_solide_23_8_15_9["SOLIDE ValueY"].apply(lambda x: x.replace("," , "."))
data_puissance_23_8_a_15_9["PUISSANCE ValueY"] = data_puissance_23_8_a_15_9["PUISSANCE ValueY"].apply(lambda x: x.replace("," , "."))

Change the type from "object" to "float" for the Value Columns

In [13]:
data_courant_23_8_a_15_9["COURANT ValueY"] = data_courant_23_8_a_15_9["COURANT ValueY"].astype(float)
data_Debit_eau_23_8_15_9["DEBIT EAU ValueY"] = data_Debit_eau_23_8_15_9["DEBIT EAU ValueY"].astype(float)
data_Debit_solide_23_8_15_9["SOLIDE ValueY"] = data_Debit_solide_23_8_15_9["SOLIDE ValueY"].astype(float)
data_puissance_23_8_a_15_9["PUISSANCE ValueY"] = data_puissance_23_8_a_15_9["PUISSANCE ValueY"].astype(float)

Shape of every csv file

In [14]:
print(data_courant_23_8_a_15_9.shape)
print(data_Debit_eau_23_8_15_9.shape)
print(data_Debit_solide_23_8_15_9.shape)
print(data_refus_tamis_23_8_a_15_9.shape)
print(data_puissance_23_8_a_15_9.shape)

(3902314, 2)
(995400, 2)
(995400, 4)
(189, 3)
(3909980, 2)

The max and the min

In [15]:
print("Courant : ")
print(data_courant_23_8_a_15_9['COURANT Time'].min())
print(data_courant_23_8_a_15_9['COURANT Time'].max())
print("Débit Eau")
print(data_Debit_eau_23_8_15_9['DEBIT EAU Time'].min())
print(data_Debit_eau_23_8_15_9['DEBIT EAU Time'].max())
print("Débit Solide")
print(data_Debit_solide_23_8_15_9['SOLIDE Time'].min())
print(data_Debit_solide_23_8_15_9['SOLIDE Time'].max())
print("Puissance")
print(data_puissance_23_8_a_15_9['PUISSANCE Time'].min())
print(data_puissance_23_8_a_15_9['PUISSANCE Time'].max())

Courant :
2022-08-23 14:50:42
2022-09-15 04:50:41
Débit Eau
2022-08-23 17:02:30
2022-09-15 18:02:28
Débit Solide
2022-08-23 17:01:18
2022-09-15 18:01:16
Puissance
2022-08-23 13:46:49
2022-09-15 04:50:41

In [16]:
def second_to_minute_3(data):
    columns = data.columns
    time_start = pd.to_datetime("2022-08-23 13:46:00")
    time_end = pd.to_datetime("2022-09-15 18:02:00")
    list_time = []
    list_value = []
    list_value_2 = []
    while(time_start <= time_end):
        interv = data[data[columns[0]].between(time_start,time_start + timedelta(minutes=1))]
        if interv.shape[0] == 0:
            list_value.append(float("nan"))
        else:
            list_value.append(interv[columns[1]].mean())
        list_time.append(time_start)
        if len(columns) == 4:
            list_value_2.append(interv[columns[3]].mean())
        time_start = time_start + timedelta(minutes=1)
    if len(columns) == 2:
        new_data = pd.DataFrame(data=zip(list_time,list_value),columns=[columns[0],columns[1]])
    elif len(columns) == 4:
        new_data = pd.DataFrame(data=zip(list_time,list_value,list_value_2),columns=[columns[0],columns[1],columns[3]])
    return new_data

In [17]:
new_data_courant_23_8_a_15_9 = second_to_minute_3(data_courant_23_8_a_15_9)
new_data_Debit_eau_23_8_15_9 = second_to_minute_3(data_Debit_eau_23_8_15_9)
new_data_Debit_solide_23_8_15_9 = second_to_minute_3(data_Debit_solide_23_8_15_9)
new_data_puissance_23_8_a_15_9 = second_to_minute_3(data_puissance_23_8_a_15_9)

In [18]:
print(new_data_courant_23_8_a_15_9)
print(new_data_Debit_eau_23_8_15_9)
print(new_data_Debit_solide_23_8_15_9)
print(new_data_puissance_23_8_a_15_9)

             COURANT Time  COURANT ValueY
0     2022-08-23 13:46:00             NaN
1     2022-08-23 13:47:00             NaN
2     2022-08-23 13:48:00             NaN
3     2022-08-23 13:49:00             NaN
4     2022-08-23 13:50:00             NaN
...                   ...             ...
33372 2022-09-15 17:58:00             NaN
33373 2022-09-15 17:59:00             NaN
33374 2022-09-15 18:00:00             NaN
33375 2022-09-15 18:01:00             NaN
33376 2022-09-15 18:02:00             NaN

[33377 rows x 2 columns]
           DEBIT EAU Time  DEBIT EAU ValueY
0     2022-08-23 13:46:00               NaN
1     2022-08-23 13:47:00               NaN
2     2022-08-23 13:48:00               NaN
3     2022-08-23 13:49:00               NaN
4     2022-08-23 13:50:00               NaN
...                   ...               ...
33372 2022-09-15 17:58:00         11.085793
33373 2022-09-15 17:59:00         11.401396
33374 2022-09-15 18:00:00         11.526471
33375 2022-09-15 18:01:00         11.307124
33376 2022-09-15 18:02:00         10.782697

[33377 rows x 2 columns]
              SOLIDE Time  SOLIDE ValueY  SP_INT ValueY
0     2022-08-23 13:46:00            NaN            NaN
1     2022-08-23 13:47:00            NaN            NaN
2     2022-08-23 13:48:00            NaN            NaN
3     2022-08-23 13:49:00            NaN            NaN
4     2022-08-23 13:50:00            NaN            NaN
...                   ...            ...            ...
33372 2022-09-15 17:58:00     116.198686          115.0
33373 2022-09-15 17:59:00     114.182265          115.0
33374 2022-09-15 18:00:00     112.822137          115.0
33375 2022-09-15 18:01:00     116.986561          115.0
33376 2022-09-15 18:02:00            NaN            NaN

[33377 rows x 3 columns]
           PUISSANCE Time  PUISSANCE ValueY
0     2022-08-23 13:46:00        586.605394
1     2022-08-23 13:47:00        592.525067
2     2022-08-23 13:48:00        583.371907
3     2022-08-23 13:49:00        592.231900
4     2022-08-23 13:50:00        580.151609
...                   ...               ...
33372 2022-09-15 17:58:00               NaN
33373 2022-09-15 17:59:00               NaN
33374 2022-09-15 18:00:00               NaN
33375 2022-09-15 18:01:00               NaN
33376 2022-09-15 18:02:00               NaN

[33377 rows x 2 columns]

In [ ]:
print(new_data_courant_23_8_a_15_9["COURANT ValueY"].isna().sum())
#new_data_courant_23_8_a_15_9.head(50)

In [20]:
new_data_courant_23_8_a_15_9.rename(columns={"COURANT Time": "Time"}, inplace=True)
new_data_Debit_eau_23_8_15_9.rename(columns={"DEBIT EAU Time": "Time"}, inplace=True)
new_data_Debit_solide_23_8_15_9.rename(columns={"SOLIDE Time": "Time"}, inplace=True)
new_data_puissance_23_8_a_15_9.rename(columns={"PUISSANCE Time": "Time"}, inplace=True)

In [21]:
data_23_08_a_15_09 = pd.merge(pd.merge(new_data_courant_23_8_a_15_9,new_data_Debit_eau_23_8_15_9,on='Time'),pd.merge(new_data_Debit_solide_23_8_15_9,new_data_puissance_23_8_a_15_9,on='Time'),on="Time")

In [22]:
data_23_08_a_15_09

,Time,COURANT ValueY,DEBIT EAU ValueY,SOLIDE ValueY,SP_INT ValueY,PUISSANCE ValueY
0,2022-08-23 13:46:00,NaN,NaN,NaN,NaN,586.605394
1,2022-08-23 13:47:00,NaN,NaN,NaN,NaN,592.525067
2,2022-08-23 13:48:00,NaN,NaN,NaN,NaN,583.371907
3,2022-08-23 13:49:00,NaN,NaN,NaN,NaN,592.231900
4,2022-08-23 13:50:00,NaN,NaN,NaN,NaN,580.151609
...,...,...,...,...,...,...
33372,2022-09-15 17:58:00,NaN,11.085793,116.198686,115.0,NaN
33373,2022-09-15 17:59:00,NaN,11.401396,114.182265,115.0,NaN
33374,2022-09-15 18:00:00,NaN,11.526471,112.822137,115.0,NaN
33375,2022-09-15 18:01:00,NaN,11.307124,116.986561,115.0,NaN
33376,2022-09-15 18:02:00,NaN,10.782697,NaN,NaN,NaN

In [23]:
data_23_08_a_15_09.to_csv("data_23_08_a_15_09.csv")

28_01 --> 03_02

Read csv files

In [3]:
data_courant_28_1_a_03_2 = pd.read_csv("De 28_01 à 03_02 2022\Courant\COURANT BROYEUR QA.csv", encoding='utf-16',sep="\t") 

data_Debit_eau_28_1_a_03_2 = pd.read_csv("De 28_01 à 03_02 2022\Débit Eau\DEBIT EAU ENTREE QA.csv",encoding='utf-16',sep="\t") 

data_Debit_solide_28_1_a_03_2 = pd.read_csv("De 28_01 à 03_02 2022\Débit Solide\DEBIT SOLIDE QA.csv",encoding='utf-16', sep= '\t') 

data_refus_tamis_janvier = pd.read_excel("De 28_01 à 03_02 2022\Refus Tamis\TB_D80_et_performances_Usine_Janvier_2022.xlsx")
data_refus_tamis_fevrier = pd.read_excel("De 28_01 à 03_02 2022\Refus Tamis\TB_D80_et_performances_Usine_Février_2022.xlsx")

data_puissance_QA_28_1_03_2 = pd.read_csv("De 28_01 à 03_02 2022\Puissance\PUISSANCE BROYEUR QA.csv",encoding='utf-16',sep="\t")

In [4]:
print("-----------------Courant-------------------------------")
print(data_courant_28_1_a_03_2)


print("-----------------Debit eau-------------------------------")
print(data_Debit_eau_28_1_a_03_2)


print("-----------------Debit solide-------------------------------")
print(data_Debit_solide_28_1_a_03_2)


print("-----------------Refus tamis-------------------------------")
print(data_refus_tamis_janvier.head(10))
print(data_refus_tamis_fevrier.head(10))

print("-----------------Puissance-------------------------------")
print(data_puissance_QA_28_1_03_2)

-----------------Courant-------------------------------
                COURANT Time    COURANT ValueY
0        28/01/2022 00:00:08  67,2531127929688
1        28/01/2022 00:00:08  67,2531127929688
2        28/01/2022 00:00:09  67,2531127929688
3        28/01/2022 00:00:09  67,2531127929688
4        28/01/2022 00:00:10  67,2531127929688
...                      ...               ...
1326585  04/02/2022 17:00:05  71,7919616699219
1326586  04/02/2022 17:00:06   62,867259979248
1326587  04/02/2022 17:00:06  61,2081146240234
1326588  04/02/2022 17:00:07  72,0775451660156
1326589  04/02/2022 17:00:07  66,6275329589844

[1326590 rows x 2 columns]
-----------------Debit eau-------------------------------
             DEBIT EAU Time  DEBIT EAU ValueY     SP_INT_AUTO Time  \
0       28/01/2022 00:00:57  10,1851854324341  28/01/2022 00:00:57
1       28/01/2022 00:00:59  10,1851854324341  28/01/2022 00:00:59
2       28/01/2022 00:01:01  10,1851854324341  28/01/2022 00:01:01
3       28/01/2022 00:01:03  10,1851854324341  28/01/2022 00:01:03
4       28/01/2022 00:01:05  10,1851854324341  28/01/2022 00:01:05
...                     ...               ...                  ...
332243  04/02/2022 17:00:47  9,37861728668213  04/02/2022 17:00:47
332244  04/02/2022 17:00:49  9,40755271911621  04/02/2022 17:00:49
332245  04/02/2022 17:00:51  9,35329914093018  04/02/2022 17:00:51
332246  04/02/2022 17:00:53  9,38585090637207  04/02/2022 17:00:53
332247  04/02/2022 17:00:55             9,375  04/02/2022 17:00:55

       SP_INT_AUTO ValueY
0                      10
1                      10
2                      10
3                      10
4                      10
...                   ...
332243                9,5
332244                9,5
332245                9,5
332246                9,5
332247                9,5

[332248 rows x 4 columns]
-----------------Debit solide-------------------------------
                SOLIDE Time     SOLIDE ValueY          SP_INT Time  \
0       28/01/2022 00:00:01  121,003326416016  28/01/2022 00:00:01
1       28/01/2022 00:00:03  121,003326416016  28/01/2022 00:00:03
2       28/01/2022 00:00:05  121,003326416016  28/01/2022 00:00:05
3       28/01/2022 00:00:07  121,003326416016  28/01/2022 00:00:07
4       28/01/2022 00:00:09  121,003326416016  28/01/2022 00:00:09
...                     ...               ...                  ...
304825  04/02/2022 01:20:51  112,802017211914  04/02/2022 01:20:51
304826  04/02/2022 01:20:53  111,762153625488  04/02/2022 01:20:53
304827  04/02/2022 01:20:55  110,152633666992  04/02/2022 01:20:55
304828  04/02/2022 01:20:57  109,881362915039  04/02/2022 01:20:57
304829  04/02/2022 01:20:59  109,709564208984  04/02/2022 01:20:59

        SP_INT ValueY
0                 120
1                 120
2                 120
3                 120
4                 120
...               ...
304825            110
304826            110
304827            110
304828            110
304829            110

[304830 rows x 4 columns]
-----------------Refus tamis-------------------------------
   Unnamed: 0           Unnamed: 1 Unnamed: 2                Unnamed: 3
0         NaN                  NaN        NaN                       NaN
1         NaN                Jours      Poste  Refus Tamis +500 en % QA
2         NaN                  NaN        NaN                       NaN
3         NaN  2022-01-01 00:00:00          1                       NaN
4         NaN                  NaN          2                       NaN
5         NaN                  NaN          3                     25.81
6         NaN  2022-01-02 00:00:00          1                 30.733229
7         NaN                  NaN          2                 25.703125
8         NaN                  NaN          3                 26.321244
9         NaN  2022-01-03 00:00:00          1                 31.490159
   Unnamed: 0           Unnamed: 1 Unnamed: 2                Unnamed: 3
0         NaN                  NaN        NaN                       NaN
1         NaN                Jours      Poste  Refus Tamis +500 en % QA
2         NaN                  NaN        NaN                       NaN
3         NaN  2022-02-01 00:00:00          1                 26.205511
4         NaN                  NaN          2                 27.455296
5         NaN                  NaN          3                 29.126214
6         NaN  2022-02-02 00:00:00          1                 18.786127
7         NaN                  NaN          2                 23.913043
8         NaN                  NaN          3                 25.235634
9         NaN  2022-02-03 00:00:00          1                 21.499449
-----------------Puissance-------------------------------
              PUISSANCE Time  PUISSANCE ValueY
0        28/01/2022 00:00:08  576,604736328125
1        28/01/2022 00:00:08  576,604736328125
2        28/01/2022 00:00:09  576,604736328125
3        28/01/2022 00:00:09  576,604736328125
4        28/01/2022 00:00:10  576,604736328125
...                      ...               ...
1326585  04/02/2022 17:00:05  615,519165039063
1326586  04/02/2022 17:00:06  591,500061035156
1326587  04/02/2022 17:00:06  524,776977539063
1326588  04/02/2022 17:00:07  496,502105712891
1326589  04/02/2022 17:00:07  571,241271972656

[1326590 rows x 2 columns]

In [5]:
process_refu_tamis(data_refus_tamis_janvier)
process_refu_tamis(data_refus_tamis_fevrier)
print(data_refus_tamis_janvier)
print(data_refus_tamis_fevrier)

                  Jours Poste Refus Tamis +500 en % QA
3   2022-01-01 00:00:00     1                      NaN
4   2022-01-01 00:00:00     2                      NaN
5   2022-01-01 00:00:00     3                    25.81
6   2022-01-02 00:00:00     1                30.733229
7   2022-01-02 00:00:00     2                25.703125
..                  ...   ...                      ...
94  2022-01-31 00:00:00     2                29.193206
95  2022-01-31 00:00:00     3                31.105089
96              MOYENNE   NaN                25.956199
97              MOYENNE   NaN                15.255906
98              MOYENNE   NaN                 35.46169

[96 rows x 3 columns]
                  Jours Poste Refus Tamis +500 en % QA
3   2022-02-01 00:00:00     1                26.205511
4   2022-02-01 00:00:00     2                27.455296
5   2022-02-01 00:00:00     3                29.126214
6   2022-02-02 00:00:00     1                18.786127
7   2022-02-02 00:00:00     2                23.913043
..                  ...   ...                      ...
85  2022-02-28 00:00:00     2                33.198507
86  2022-02-28 00:00:00     3                28.062157
87              MOYENNE   NaN                24.345225
88              MOYENNE   NaN                15.627498
89              MOYENNE   NaN                33.198507

[87 rows x 3 columns]

print the types of every column

In [6]:
print(data_courant_28_1_a_03_2.dtypes)


print(data_Debit_eau_28_1_a_03_2.dtypes)


print(data_Debit_solide_28_1_a_03_2.dtypes)


print(data_refus_tamis_janvier.dtypes)
print(data_refus_tamis_fevrier.dtypes)

print(data_puissance_QA_28_1_03_2.dtypes)

COURANT Time      object
COURANT ValueY    object
dtype: object
DEBIT EAU Time        object
DEBIT EAU ValueY      object
SP_INT_AUTO Time      object
SP_INT_AUTO ValueY    object
dtype: object
SOLIDE Time      object
SOLIDE ValueY    object
SP_INT Time      object
SP_INT ValueY     int64
dtype: object
Jours                       object
Poste                       object
Refus Tamis +500 en % QA    object
dtype: object
Jours                       object
Poste                       object
Refus Tamis +500 en % QA    object
dtype: object
PUISSANCE Time      object
PUISSANCE ValueY    object
dtype: object

In [7]:
frames = (data_refus_tamis_janvier , data_refus_tamis_fevrier)
data_refus_tamis_28_1_03_2 = pd.concat(frames)
data_refus_tamis_28_1_03_2

                  Jours Poste Refus Tamis +500 en % QA
3   2022-01-01 00:00:00     1                      NaN
4   2022-01-01 00:00:00     2                      NaN
5   2022-01-01 00:00:00     3                    25.81
6   2022-01-02 00:00:00     1                30.733229
7   2022-01-02 00:00:00     2                25.703125
..                  ...   ...                      ...
85  2022-02-28 00:00:00     2                33.198507
86  2022-02-28 00:00:00     3                28.062157
87              MOYENNE   NaN                24.345225
88              MOYENNE   NaN                15.627498
89              MOYENNE   NaN                33.198507

[183 rows x 3 columns]

In [8]:
data_courant_28_1_a_03_2['COURANT Time'] = pd.to_datetime(data_courant_28_1_a_03_2['COURANT Time'], format="%d/%m/%Y %H:%M:%S")
data_Debit_eau_28_1_a_03_2['DEBIT EAU Time'] = pd.to_datetime(data_Debit_eau_28_1_a_03_2['DEBIT EAU Time'], format="%d/%m/%Y %H:%M:%S")
data_Debit_solide_28_1_a_03_2['SOLIDE Time'] = pd.to_datetime(data_Debit_solide_28_1_a_03_2['SOLIDE Time'], format="%d/%m/%Y %H:%M:%S")
data_puissance_QA_28_1_03_2['PUISSANCE Time'] = pd.to_datetime(data_puissance_QA_28_1_03_2['PUISSANCE Time'], format="%d/%m/%Y %H:%M:%S")
#data_refus_tamis_28_1_03_2['Jours'] = pd.to_datetime(data_refus_tamis_28_1_03_2['Jours'], format="%Y/%m/%d %H:%M:%S")

In [9]:
print(data_courant_28_1_a_03_2.dtypes)
print(data_Debit_eau_28_1_a_03_2.dtypes)
print(data_Debit_solide_28_1_a_03_2.dtypes)
print(data_puissance_QA_28_1_03_2.dtypes)
#print(data_refus_tamis_28_1_03_2.dtypes)

COURANT Time      datetime64[ns]
COURANT ValueY            object
dtype: object
DEBIT EAU Time        datetime64[ns]
DEBIT EAU ValueY              object
SP_INT_AUTO Time              object
SP_INT_AUTO ValueY            object
dtype: object
SOLIDE Time      datetime64[ns]
SOLIDE ValueY            object
SP_INT Time              object
SP_INT ValueY             int64
dtype: object
PUISSANCE Time      datetime64[ns]
PUISSANCE ValueY            object
dtype: object

Replace the "," by "."

In [10]:
data_courant_28_1_a_03_2["COURANT ValueY"] = data_courant_28_1_a_03_2["COURANT ValueY"].apply(lambda x: x.replace("," , "."))
data_Debit_eau_28_1_a_03_2["DEBIT EAU ValueY"] = data_Debit_eau_28_1_a_03_2["DEBIT EAU ValueY"].apply(lambda x: x.replace("," , "."))
data_Debit_eau_28_1_a_03_2["SP_INT_AUTO ValueY"] = data_Debit_eau_28_1_a_03_2["SP_INT_AUTO ValueY"].apply(lambda x: x.replace("," , "."))
data_Debit_solide_28_1_a_03_2["SOLIDE ValueY"] = data_Debit_solide_28_1_a_03_2["SOLIDE ValueY"].apply(lambda x: x.replace("," , "."))
data_puissance_QA_28_1_03_2["PUISSANCE ValueY"] = data_puissance_QA_28_1_03_2["PUISSANCE ValueY"].apply(lambda x: x.replace("," , "."))

Change the type from "object" to "float" for the Value Columns

In [11]:
data_courant_28_1_a_03_2["COURANT ValueY"] = data_courant_28_1_a_03_2["COURANT ValueY"].astype(float)
data_Debit_eau_28_1_a_03_2["DEBIT EAU ValueY"] = data_Debit_eau_28_1_a_03_2["DEBIT EAU ValueY"].astype(float)
data_Debit_eau_28_1_a_03_2["SP_INT_AUTO ValueY"] = data_Debit_eau_28_1_a_03_2["SP_INT_AUTO ValueY"].astype(float)
data_Debit_solide_28_1_a_03_2["SOLIDE ValueY"] = data_Debit_solide_28_1_a_03_2["SOLIDE ValueY"].astype(float)
data_puissance_QA_28_1_03_2["PUISSANCE ValueY"] = data_puissance_QA_28_1_03_2["PUISSANCE ValueY"].astype(float)

In [12]:
print(data_courant_28_1_a_03_2.dtypes)


print(data_Debit_eau_28_1_a_03_2.dtypes)


print(data_Debit_solide_28_1_a_03_2.dtypes)


print(data_refus_tamis_janvier.dtypes)
print(data_refus_tamis_fevrier.dtypes)

print(data_puissance_QA_28_1_03_2.dtypes)

COURANT Time      datetime64[ns]
COURANT ValueY           float64
dtype: object
DEBIT EAU Time        datetime64[ns]
DEBIT EAU ValueY             float64
SP_INT_AUTO Time              object
SP_INT_AUTO ValueY           float64
dtype: object
SOLIDE Time      datetime64[ns]
SOLIDE ValueY           float64
SP_INT Time              object
SP_INT ValueY             int64
dtype: object
Jours                       object
Poste                       object
Refus Tamis +500 en % QA    object
dtype: object
Jours                       object
Poste                       object
Refus Tamis +500 en % QA    object
dtype: object
PUISSANCE Time      datetime64[ns]
PUISSANCE ValueY           float64
dtype: object

data_puissance_QA_28_1_03_2

In [13]:
print(data_courant_28_1_a_03_2.shape)
print(data_Debit_eau_28_1_a_03_2.shape)
print(data_Debit_solide_28_1_a_03_2.shape)
print(data_refus_tamis_28_1_03_2.shape)
print(data_puissance_QA_28_1_03_2.shape)

(1326590, 2)
(332248, 4)
(304830, 4)
(183, 3)
(1326590, 2)

In [14]:
print("Courant : ")
print(data_courant_28_1_a_03_2['COURANT Time'].min())
print(data_courant_28_1_a_03_2['COURANT Time'].max())
print("Débit Eau")
print(data_Debit_eau_28_1_a_03_2['DEBIT EAU Time'].min())
print(data_Debit_eau_28_1_a_03_2['DEBIT EAU Time'].max())
print("Débit Solide")
print(data_Debit_solide_28_1_a_03_2['SOLIDE Time'].min())
print(data_Debit_solide_28_1_a_03_2['SOLIDE Time'].max())
print("Puissance")
print(data_puissance_QA_28_1_03_2['PUISSANCE Time'].min())
print(data_puissance_QA_28_1_03_2['PUISSANCE Time'].max())

Courant :
2022-01-28 00:00:08
2022-02-04 17:00:07
Débit Eau
2022-01-28 00:00:57
2022-02-04 17:00:55
Débit Solide
2022-01-28 00:00:01
2022-02-04 01:20:59
Puissance
2022-01-28 00:00:08
2022-02-04 17:00:07

In [15]:
def second_to_minute_4(data):
    columns = data.columns
    time_start = pd.to_datetime("2022-01-28 00:00:00")
    time_end = pd.to_datetime("2022-02-04 17:00:00")
    list_time = []
    list_value = []
    list_value_2 = []
    while(time_start <= time_end):
        interv = data[data[columns[0]].between(time_start,time_start + timedelta(minutes=1))]
        if interv.shape[0] == 0:
            list_value.append(float("nan"))
        else:
            list_value.append(interv[columns[1]].mean())
        list_time.append(time_start)
        if len(columns) == 4:
            list_value_2.append(interv[columns[3]].mean())
        time_start = time_start + timedelta(minutes=1)
    if len(columns) == 2:
        new_data = pd.DataFrame(data=zip(list_time,list_value),columns=[columns[0],columns[1]])
    elif len(columns) == 4:
        new_data = pd.DataFrame(data=zip(list_time,list_value,list_value_2),columns=[columns[0],columns[1],columns[3]])
    return new_data

In [16]:
new_data_courant_28_1_a_03_2 = second_to_minute_4(data_courant_28_1_a_03_2)
new_data_Debit_eau_28_1_a_03_2 = second_to_minute_4(data_Debit_eau_28_1_a_03_2)
new_data_Debit_solide_28_1_a_03_2 = second_to_minute_4(data_Debit_solide_28_1_a_03_2)
new_data_puissance_28_1_a_03_2 = second_to_minute_4(data_puissance_QA_28_1_03_2)

In [17]:
print(new_data_courant_28_1_a_03_2)
print(new_data_Debit_eau_28_1_a_03_2)
print(new_data_Debit_solide_28_1_a_03_2)
print(new_data_puissance_28_1_a_03_2)

             COURANT Time  COURANT ValueY
0     2022-01-28 00:00:00       67.253113
1     2022-01-28 00:01:00       67.253113
2     2022-01-28 00:02:00       67.253113
3     2022-01-28 00:03:00       67.253113
4     2022-01-28 00:04:00       67.253113
...                   ...             ...
11096 2022-02-04 16:56:00       66.443994
11097 2022-02-04 16:57:00       66.702970
11098 2022-02-04 16:58:00       66.539776
11099 2022-02-04 16:59:00       67.152340
11100 2022-02-04 17:00:00       67.503427

[11101 rows x 2 columns]
           DEBIT EAU Time  DEBIT EAU ValueY  SP_INT_AUTO ValueY
0     2022-01-28 00:00:00         10.185185                10.0
1     2022-01-28 00:01:00         10.185185                10.0
2     2022-01-28 00:02:00         10.185185                10.0
3     2022-01-28 00:03:00         10.185185                10.0
4     2022-01-28 00:04:00         10.185185                10.0
...                   ...               ...                 ...
11096 2022-02-04 16:56:00          9.648076                 9.5
11097 2022-02-04 16:57:00          9.724392                 9.5
11098 2022-02-04 16:58:00          9.275415                 9.5
11099 2022-02-04 16:59:00          8.460648                 9.5
11100 2022-02-04 17:00:00          9.447209                 9.5

[11101 rows x 3 columns]
              SOLIDE Time  SOLIDE ValueY  SP_INT ValueY
0     2022-01-28 00:00:00     121.003326          120.0
1     2022-01-28 00:01:00     121.003326          120.0
2     2022-01-28 00:02:00     121.003326          120.0
3     2022-01-28 00:03:00     121.003326          120.0
4     2022-01-28 00:04:00     121.003326          120.0
...                   ...            ...            ...
11096 2022-02-04 16:56:00            NaN            NaN
11097 2022-02-04 16:57:00            NaN            NaN
11098 2022-02-04 16:58:00            NaN            NaN
11099 2022-02-04 16:59:00            NaN            NaN
11100 2022-02-04 17:00:00            NaN            NaN

[11101 rows x 3 columns]
           PUISSANCE Time  PUISSANCE ValueY
0     2022-01-28 00:00:00        576.604736
1     2022-01-28 00:01:00        576.604736
2     2022-01-28 00:02:00        576.604736
3     2022-01-28 00:03:00        576.604736
4     2022-01-28 00:04:00        576.604736
...                   ...               ...
11096 2022-02-04 16:56:00        562.365687
11097 2022-02-04 16:57:00        570.214521
11098 2022-02-04 16:58:00        565.358756
11099 2022-02-04 16:59:00        575.820535
11100 2022-02-04 17:00:00        572.784298

[11101 rows x 2 columns]

In [18]:
new_data_courant_28_1_a_03_2.rename(columns={"COURANT Time": "Time"}, inplace=True)
new_data_Debit_eau_28_1_a_03_2.rename(columns={"DEBIT EAU Time": "Time"}, inplace=True)
new_data_Debit_solide_28_1_a_03_2.rename(columns={"SOLIDE Time": "Time"}, inplace=True)
new_data_puissance_28_1_a_03_2.rename(columns={"PUISSANCE Time": "Time"}, inplace=True)

In [19]:
data_28_01_a_03_02 = pd.merge(pd.merge(new_data_courant_28_1_a_03_2,new_data_Debit_eau_28_1_a_03_2,on='Time'),pd.merge(new_data_Debit_solide_28_1_a_03_2,new_data_puissance_28_1_a_03_2,on='Time'),on="Time")

In [20]:
data_28_01_a_03_02

,Time,COURANT ValueY,DEBIT EAU ValueY,SP_INT_AUTO ValueY,SOLIDE ValueY,SP_INT ValueY,PUISSANCE ValueY
0,2022-01-28 00:00:00,67.253113,10.185185,10.0,121.003326,120.0,576.604736
1,2022-01-28 00:01:00,67.253113,10.185185,10.0,121.003326,120.0,576.604736
2,2022-01-28 00:02:00,67.253113,10.185185,10.0,121.003326,120.0,576.604736
3,2022-01-28 00:03:00,67.253113,10.185185,10.0,121.003326,120.0,576.604736
4,2022-01-28 00:04:00,67.253113,10.185185,10.0,121.003326,120.0,576.604736
...,...,...,...,...,...,...,...
11096,2022-02-04 16:56:00,66.443994,9.648076,9.5,NaN,NaN,562.365687
11097,2022-02-04 16:57:00,66.702970,9.724392,9.5,NaN,NaN,570.214521
11098,2022-02-04 16:58:00,66.539776,9.275415,9.5,NaN,NaN,565.358756
11099,2022-02-04 16:59:00,67.152340,8.460648,9.5,NaN,NaN,575.820535
11100,2022-02-04 17:00:00,67.503427,9.447209,9.5,NaN,NaN,572.784298

In [21]:
data_28_01_a_03_02.to_csv("data_28_01_a_03_02.csv")