In [1]:
import pandas as pd
import numpy as np
from datetime import timedelta

In [2]:
data_28_01_a_03_02 = pd.read_csv("data_28_01_a_03_02.csv")
data_11_02_a_17_02 = pd.read_csv("data_11_02_a_17_02.csv")
data_23_08_a_15_09 = pd.read_csv("data_23_08_a_15_09.csv")
data_15_09_a_20_10 = pd.read_csv("data_15_09_a_20_10.csv")

In [3]:
data_28_01_a_03_02

,Unnamed: 0,Time,COURANT ValueY,DEBIT EAU ValueY,SP_INT_AUTO ValueY,SOLIDE ValueY,SP_INT ValueY,PUISSANCE ValueY
0,0,2022-01-28 00:00:00,67.253113,10.185185,10.0,121.003326,120.0,576.604736
1,1,2022-01-28 00:01:00,67.253113,10.185185,10.0,121.003326,120.0,576.604736
2,2,2022-01-28 00:02:00,67.253113,10.185185,10.0,121.003326,120.0,576.604736
3,3,2022-01-28 00:03:00,67.253113,10.185185,10.0,121.003326,120.0,576.604736
4,4,2022-01-28 00:04:00,67.253113,10.185185,10.0,121.003326,120.0,576.604736
...,...,...,...,...,...,...,...,...
11096,11096,2022-02-04 16:56:00,66.443994,9.648076,9.5,NaN,NaN,562.365687
11097,11097,2022-02-04 16:57:00,66.702970,9.724392,9.5,NaN,NaN,570.214521
11098,11098,2022-02-04 16:58:00,66.539776,9.275415,9.5,NaN,NaN,565.358756
11099,11099,2022-02-04 16:59:00,67.152340,8.460648,9.5,NaN,NaN,575.820535
11100,11100,2022-02-04 17:00:00,67.503427,9.447209,9.5,NaN,NaN,572.784298

In [4]:
data_11_02_a_17_02

,Unnamed: 0,Time,COURANT ValueY,DEBIT EAU ValueY,SOLIDE ValueY,SP_INT ValueY,PUISSANCE ValueY
0,0,2022-02-11 00:00:00,65.442617,9.366681,115.298274,115.0,559.952023
1,1,2022-02-11 00:01:00,65.784166,8.775439,113.518156,115.0,562.290662
2,2,2022-02-11 00:02:00,65.831569,9.686415,113.878942,115.0,562.912594
3,3,2022-02-11 00:03:00,64.970144,9.813006,117.350561,115.0,557.878828
4,4,2022-02-11 00:04:00,65.341595,9.897039,113.183894,115.0,561.615206
...,...,...,...,...,...,...,...
9536,9536,2022-02-17 14:56:00,66.063068,9.216323,111.649853,NaN,564.337326
9537,9537,2022-02-17 14:57:00,65.189325,9.203489,110.982478,NaN,558.512230
9538,9538,2022-02-17 14:58:00,66.403390,9.226007,109.076022,NaN,569.896756
9539,9539,2022-02-17 14:59:00,66.516785,9.297878,109.423127,NaN,569.889818
9540,9540,2022-02-17 15:00:00,66.288485,9.106144,111.625476,NaN,573.881831

In [5]:
data_23_08_a_15_09

,Unnamed: 0,Time,COURANT ValueY,DEBIT EAU ValueY,SOLIDE ValueY,SP_INT ValueY,PUISSANCE ValueY
0,0,2022-08-23 13:46:00,NaN,NaN,NaN,NaN,586.605394
1,1,2022-08-23 13:47:00,NaN,NaN,NaN,NaN,592.525067
2,2,2022-08-23 13:48:00,NaN,NaN,NaN,NaN,583.371907
3,3,2022-08-23 13:49:00,NaN,NaN,NaN,NaN,592.231900
4,4,2022-08-23 13:50:00,NaN,NaN,NaN,NaN,580.151609
...,...,...,...,...,...,...,...
33372,33372,2022-09-15 17:58:00,NaN,11.085793,116.198686,115.0,NaN
33373,33373,2022-09-15 17:59:00,NaN,11.401396,114.182265,115.0,NaN
33374,33374,2022-09-15 18:00:00,NaN,11.526471,112.822137,115.0,NaN
33375,33375,2022-09-15 18:01:00,NaN,11.307124,116.986561,115.0,NaN
33376,33376,2022-09-15 18:02:00,NaN,10.782697,NaN,NaN,NaN

In [6]:
data_15_09_a_20_10

,Unnamed: 0,Time,COURANT ValueY,DEBIT EAU ValueY,SOLIDE ValueY,PUISSANCE ValueY
0,0,2022-09-15 14:40:00,NaN,NaN,114.791306,NaN
1,1,2022-09-15 14:41:00,NaN,NaN,116.841270,NaN
2,2,2022-09-15 14:42:00,NaN,NaN,114.797431,NaN
3,3,2022-09-15 14:43:00,NaN,NaN,114.255771,NaN
4,4,2022-09-15 14:44:00,NaN,NaN,117.610444,NaN
...,...,...,...,...,...,...
50537,50537,2022-10-20 16:57:00,NaN,NaN,NaN,507.211636
50538,50538,2022-10-20 16:58:00,NaN,NaN,NaN,511.160186
50539,50539,2022-10-20 16:59:00,NaN,NaN,NaN,509.005283
50540,50540,2022-10-20 17:00:00,NaN,NaN,NaN,510.360491
50541,50541,2022-10-20 17:01:00,NaN,NaN,NaN,509.105051

In [7]:
mu=0.0
std = 0.005
def gaussian_noise(x,mu,std):
    noise = np.random.normal(mu, std)
    x_noisy = x + noise
    return x_noisy

In [8]:
gaussian_noise(26.205511,mu,std)

26.20913441200056

11_02 à 17_02

In [9]:
data_refus_tamis = pd.read_excel("De 11_02 à 17_02 2022\Refus Tamis\TB_D80_et_performances_Usine_Février_2022.xlsx")

In [10]:
def process_refu_tamis(data):
    data.dropna(how='all',inplace=True)
    del data["Unnamed: 0"]
    data.rename(columns={'Unnamed: 1':"Jours", 'Unnamed: 2':"Poste",'Unnamed: 3':"Refus Tamis +500 en % QA"}, inplace=True)
    data.drop(index=1,inplace=True)
    for i,line in enumerate(data.index):
        if data.iloc[i]["Jours"] is np.nan:
            data.iloc[i]["Jours"] = data.iloc[i-1]["Jours"]
        if (data.iloc[i]["Refus Tamis +500 en % QA"] is np.nan) and not ((pd.to_datetime(data.iloc[i]["Jours"]) >= (pd.to_datetime("2022-09-15 00:00:00"))) and (pd.to_datetime(data.iloc[i]["Jours"]) <= pd.to_datetime("2022-09-30 00:00:00"))):
            data.iloc[i]["Refus Tamis +500 en % QA"] = data.iloc[i-1]["Refus Tamis +500 en % QA"]
    data.drop(data.tail(3).index,inplace = True)
    data['Jours'] = pd.to_datetime(data['Jours'], format="%Y/%m/%d %H:%M:%S")
    data["Refus Tamis +500 en % QA"] = data["Refus Tamis +500 en % QA"].astype(float)

In [11]:
process_refu_tamis(data_refus_tamis)

In [12]:
data_refus_tamis

        Jours Poste  Refus Tamis +500 en % QA
3  2022-02-01     1                 26.205511
4  2022-02-01     2                 27.455296
5  2022-02-01     3                 29.126214
6  2022-02-02     1                 18.786127
7  2022-02-02     2                 23.913043
..        ...   ...                       ...
82 2022-02-27     2                 27.087257
83 2022-02-27     3                 29.128137
84 2022-02-28     1                 25.339690
85 2022-02-28     2                 33.198507
86 2022-02-28     3                 28.062157

[84 rows x 3 columns]

In [13]:
data_refus_tamis.dtypes

Jours                       datetime64[ns]
Poste                               object
Refus Tamis +500 en % QA           float64
dtype: object

In [14]:
data_11_02_a_17_02=data_11_02_a_17_02.assign(refus_tamis=0)

In [15]:
data_11_02_a_17_02.dtypes

Unnamed: 0            int64
Time                 object
COURANT ValueY      float64
DEBIT EAU ValueY    float64
SOLIDE ValueY       float64
SP_INT ValueY       float64
PUISSANCE ValueY    float64
refus_tamis           int64
dtype: object

In [16]:
data_11_02_a_17_02['Time'] = pd.to_datetime(data_11_02_a_17_02['Time'], format="%Y/%m/%d %H:%M:%S")

In [17]:
def add_refus_tamis(refus_tamis,data):
    for i,line in enumerate(refus_tamis.index):
        v1 = refus_tamis.iloc[i]["Jours"]
        if i !=0:
            if(v1 != refus_tamis.iloc[i-1]["Jours"]):
                data.loc[data.Time.between(v1,v1+timedelta(days=1)),'refus_tamis']= gaussian_noise(refus_tamis[refus_tamis["Jours"] == v1]["Refus Tamis +500 en % QA"].mean(),mu,std)
                v2 = v1
        else:
            data.loc[data.Time.between(v1,v1+timedelta(days=1)),'refus_tamis']= gaussian_noise(refus_tamis[refus_tamis["Jours"] == v1]["Refus Tamis +500 en % QA"].mean(),mu,std)

In [18]:
add_refus_tamis(data_refus_tamis,data_11_02_a_17_02)

In [19]:
data_11_02_a_17_02

,Unnamed: 0,Time,COURANT ValueY,DEBIT EAU ValueY,SOLIDE ValueY,SP_INT ValueY,PUISSANCE ValueY,refus_tamis
0,0,2022-02-11 00:00:00,65.442617,9.366681,115.298274,115.0,559.952023,24.644106
1,1,2022-02-11 00:01:00,65.784166,8.775439,113.518156,115.0,562.290662,24.644106
2,2,2022-02-11 00:02:00,65.831569,9.686415,113.878942,115.0,562.912594,24.644106
3,3,2022-02-11 00:03:00,64.970144,9.813006,117.350561,115.0,557.878828,24.644106
4,4,2022-02-11 00:04:00,65.341595,9.897039,113.183894,115.0,561.615206,24.644106
...,...,...,...,...,...,...,...,...
9536,9536,2022-02-17 14:56:00,66.063068,9.216323,111.649853,NaN,564.337326,18.021980
9537,9537,2022-02-17 14:57:00,65.189325,9.203489,110.982478,NaN,558.512230,18.021980
9538,9538,2022-02-17 14:58:00,66.403390,9.226007,109.076022,NaN,569.896756,18.021980
9539,9539,2022-02-17 14:59:00,66.516785,9.297878,109.423127,NaN,569.889818,18.021980
9540,9540,2022-02-17 15:00:00,66.288485,9.106144,111.625476,NaN,573.881831,18.021980

15_09 à 20_10

In [20]:
data_refus_tamis_octobre = pd.read_excel("De 15_09 à 20_10 2022\Refus Tamis\TB_D80_et_performances_Usine_Octobre_2022.xlsx")
data_refus_tamis_septembre = pd.read_excel("De 15_09 à 20_10 2022\Refus Tamis\TB_D80_et_performances_Usine_Septembre_2022.xlsx")

In [21]:
data_refus_tamis_septembre.tail(60)

    Unnamed: 0           Unnamed: 1 Unnamed: 2 Unnamed: 3
36         NaN  2022-09-12 00:00:00          1        NaN
37         NaN                  NaN          2      21.07
38         NaN                  NaN          3  16.517635
39         NaN  2022-09-13 00:00:00          1  18.950265
40         NaN                  NaN          2  22.575517
41         NaN                  NaN          3  18.565154
42         NaN  2022-09-14 00:00:00          1  21.620746
43         NaN                  NaN          2  18.565154
44         NaN                  NaN          3  21.667322
45         NaN  2022-09-15 00:00:00          1        NaN
46         NaN                  NaN          2        NaN
47         NaN                  NaN          3        NaN
48         NaN  2022-09-16 00:00:00          1        NaN
49         NaN                  NaN          2        NaN
50         NaN                  NaN          3        NaN
51         NaN  2022-09-17 00:00:00          1        NaN
52         NaN                  NaN          2        NaN
53         NaN                  NaN          3        NaN
54         NaN  2022-09-18 00:00:00          1        NaN
55         NaN                  NaN          2        NaN
56         NaN                  NaN          3        NaN
57         NaN  2022-09-19 00:00:00          1        NaN
58         NaN                  NaN          2        NaN
59         NaN                  NaN          3        NaN
60         NaN  2022-09-20 00:00:00          1        NaN
61         NaN                  NaN          2        NaN
62         NaN                  NaN          3        NaN
63         NaN  2022-09-21 00:00:00          1        NaN
64         NaN                  NaN          2        NaN
65         NaN                  NaN          3        NaN
66         NaN  2022-09-22 00:00:00          1        NaN
67         NaN                  NaN          2        NaN
68         NaN                  NaN          3        NaN
69         NaN  2022-09-23 00:00:00          1        NaN
70         NaN                  NaN          2        NaN
71         NaN                  NaN          3        NaN
72         NaN  2022-09-24 00:00:00          1        NaN
73         NaN                  NaN          2        NaN
74         NaN                  NaN          3        NaN
75         NaN  2022-09-25 00:00:00          1        NaN
76         NaN                  NaN          2        NaN
77         NaN                  NaN          3        NaN
78         NaN  2022-09-26 00:00:00          1        NaN
79         NaN                  NaN          2        NaN
80         NaN                  NaN          3        NaN
81         NaN  2022-09-27 00:00:00          1        NaN
82         NaN                  NaN          2        NaN
83         NaN                  NaN          3        NaN
84         NaN  2022-09-28 00:00:00          1        NaN
85         NaN                  NaN          2        NaN
86         NaN                  NaN          3        NaN
87         NaN  2022-09-29 00:00:00          1        NaN
88         NaN                  NaN          2        NaN
89         NaN                  NaN          3        NaN
90         NaN  2022-09-30 00:00:00          1        NaN
91         NaN                  NaN          2        NaN
92         NaN                  NaN          3        NaN
93         NaN              MOYENNE        NaN  19.457157
94         NaN                  NaN        NaN  13.326848
95         NaN                  NaN        NaN      29.03

In [22]:
process_refu_tamis(data_refus_tamis_octobre)
process_refu_tamis(data_refus_tamis_septembre)

In [23]:
print(data_refus_tamis_octobre)
print(data_refus_tamis_septembre)

        Jours Poste  Refus Tamis +500 en % QA
3  2022-10-01     1                 22.182362
4  2022-10-01     2                 19.904009
5  2022-10-01     3                 19.904009
6  2022-10-02     1                 19.904009
7  2022-10-02     2                 19.904009
..        ...   ...                       ...
91 2022-10-30     2                 19.743052
92 2022-10-30     3                 19.743052
93 2022-10-31     1                 19.743052
94 2022-10-31     2                 19.743052
95 2022-10-31     3                 19.743052

[93 rows x 3 columns]
        Jours Poste  Refus Tamis +500 en % QA
3  2022-09-01     1                     29.03
4  2022-09-01     2                     22.29
5  2022-09-01     3                     22.29
6  2022-09-02     1                     22.29
7  2022-09-02     2                     22.29
..        ...   ...                       ...
88 2022-09-29     2                       NaN
89 2022-09-29     3                       NaN
90 2022-09-30     1                       NaN
91 2022-09-30     2                       NaN
92 2022-09-30     3                       NaN

[90 rows x 3 columns]

In [24]:
data_refus_tamis_septembre.tail(50)

        Jours Poste  Refus Tamis +500 en % QA
43 2022-09-14     2                 18.565154
44 2022-09-14     3                 21.667322
45 2022-09-15     1                       NaN
46 2022-09-15     2                       NaN
47 2022-09-15     3                       NaN
48 2022-09-16     1                       NaN
49 2022-09-16     2                       NaN
50 2022-09-16     3                       NaN
51 2022-09-17     1                       NaN
52 2022-09-17     2                       NaN
53 2022-09-17     3                       NaN
54 2022-09-18     1                       NaN
55 2022-09-18     2                       NaN
56 2022-09-18     3                       NaN
57 2022-09-19     1                       NaN
58 2022-09-19     2                       NaN
59 2022-09-19     3                       NaN
60 2022-09-20     1                       NaN
61 2022-09-20     2                       NaN
62 2022-09-20     3                       NaN
63 2022-09-21     1                       NaN
64 2022-09-21     2                       NaN
65 2022-09-21     3                       NaN
66 2022-09-22     1                       NaN
67 2022-09-22     2                       NaN
68 2022-09-22     3                       NaN
69 2022-09-23     1                       NaN
70 2022-09-23     2                       NaN
71 2022-09-23     3                       NaN
72 2022-09-24     1                       NaN
73 2022-09-24     2                       NaN
74 2022-09-24     3                       NaN
75 2022-09-25     1                       NaN
76 2022-09-25     2                       NaN
77 2022-09-25     3                       NaN
78 2022-09-26     1                       NaN
79 2022-09-26     2                       NaN
80 2022-09-26     3                       NaN
81 2022-09-27     1                       NaN
82 2022-09-27     2                       NaN
83 2022-09-27     3                       NaN
84 2022-09-28     1                       NaN
85 2022-09-28     2                       NaN
86 2022-09-28     3                       NaN
87 2022-09-29     1                       NaN
88 2022-09-29     2                       NaN
89 2022-09-29     3                       NaN
90 2022-09-30     1                       NaN
91 2022-09-30     2                       NaN
92 2022-09-30     3                       NaN

In [25]:
data_15_09_a_20_10=data_15_09_a_20_10.assign(refus_tamis=0)

In [26]:
data_15_09_a_20_10.dtypes

Unnamed: 0            int64
Time                 object
COURANT ValueY      float64
DEBIT EAU ValueY    float64
SOLIDE ValueY       float64
PUISSANCE ValueY    float64
refus_tamis           int64
dtype: object

In [27]:
data_15_09_a_20_10['Time'] = pd.to_datetime(data_15_09_a_20_10['Time'], format="%Y/%m/%d %H:%M:%S")

In [28]:
add_refus_tamis(data_refus_tamis_octobre,data_15_09_a_20_10)
add_refus_tamis(data_refus_tamis_septembre,data_15_09_a_20_10)

In [29]:
data_15_09_a_20_10

,Unnamed: 0,Time,COURANT ValueY,DEBIT EAU ValueY,SOLIDE ValueY,PUISSANCE ValueY,refus_tamis
0,0,2022-09-15 14:40:00,NaN,NaN,114.791306,NaN,NaN
1,1,2022-09-15 14:41:00,NaN,NaN,116.841270,NaN,NaN
2,2,2022-09-15 14:42:00,NaN,NaN,114.797431,NaN,NaN
3,3,2022-09-15 14:43:00,NaN,NaN,114.255771,NaN,NaN
4,4,2022-09-15 14:44:00,NaN,NaN,117.610444,NaN,NaN
...,...,...,...,...,...,...,...
50537,50537,2022-10-20 16:57:00,NaN,NaN,NaN,507.211636,19.740854
50538,50538,2022-10-20 16:58:00,NaN,NaN,NaN,511.160186,19.740854
50539,50539,2022-10-20 16:59:00,NaN,NaN,NaN,509.005283,19.740854
50540,50540,2022-10-20 17:00:00,NaN,NaN,NaN,510.360491,19.740854
50541,50541,2022-10-20 17:01:00,NaN,NaN,NaN,509.105051,19.740854

23_08 à 15_09

In [30]:
data_refus_tamis_aout = pd.read_excel("De 23_08 à 15_09 2022\Refus Tamis\TB_D80_et_performances_Usine_Août_2022.xlsx")
data_refus_tamis_septembre_2 = pd.read_excel("De 23_08 à 15_09 2022\Refus Tamis\TB_D80_et_performances_Usine_Septembre_2022.xlsx")

In [31]:
process_refu_tamis(data_refus_tamis_aout)
process_refu_tamis(data_refus_tamis_septembre_2)

In [32]:
print(data_refus_tamis_aout)
print(data_refus_tamis_septembre_2)

        Jours Poste  Refus Tamis +500 en % QA
3  2022-08-01     1                 15.829722
4  2022-08-01     2                 21.457873
5  2022-08-01     3                 23.030496
6  2022-08-02     1                 19.087793
7  2022-08-02     2                 18.954439
..        ...   ...                       ...
91 2022-08-30     2                 21.484071
92 2022-08-30     3                 21.934113
93 2022-08-31     1                 15.695067
94 2022-08-31     2                 19.498698
95 2022-08-31     3                 18.869580

[93 rows x 3 columns]
        Jours Poste  Refus Tamis +500 en % QA
3  2022-09-01     1                     29.03
4  2022-09-01     2                     22.29
5  2022-09-01     3                     22.29
6  2022-09-02     1                     22.29
7  2022-09-02     2                     22.29
..        ...   ...                       ...
88 2022-09-29     2                       NaN
89 2022-09-29     3                       NaN
90 2022-09-30     1                       NaN
91 2022-09-30     2                       NaN
92 2022-09-30     3                       NaN

[90 rows x 3 columns]

In [33]:
data_23_08_a_15_09=data_23_08_a_15_09.assign(refus_tamis=0)

In [34]:
data_23_08_a_15_09.dtypes

Unnamed: 0            int64
Time                 object
COURANT ValueY      float64
DEBIT EAU ValueY    float64
SOLIDE ValueY       float64
SP_INT ValueY       float64
PUISSANCE ValueY    float64
refus_tamis           int64
dtype: object

In [35]:
data_23_08_a_15_09['Time'] = pd.to_datetime(data_23_08_a_15_09['Time'], format="%Y/%m/%d %H:%M:%S")

In [36]:
add_refus_tamis(data_refus_tamis_aout,data_23_08_a_15_09)
add_refus_tamis(data_refus_tamis_septembre_2,data_23_08_a_15_09)

In [37]:
data_23_08_a_15_09

,Unnamed: 0,Time,COURANT ValueY,DEBIT EAU ValueY,SOLIDE ValueY,SP_INT ValueY,PUISSANCE ValueY,refus_tamis
0,0,2022-08-23 13:46:00,NaN,NaN,NaN,NaN,586.605394,18.004329
1,1,2022-08-23 13:47:00,NaN,NaN,NaN,NaN,592.525067,18.004329
2,2,2022-08-23 13:48:00,NaN,NaN,NaN,NaN,583.371907,18.004329
3,3,2022-08-23 13:49:00,NaN,NaN,NaN,NaN,592.231900,18.004329
4,4,2022-08-23 13:50:00,NaN,NaN,NaN,NaN,580.151609,18.004329
...,...,...,...,...,...,...,...,...
33372,33372,2022-09-15 17:58:00,NaN,11.085793,116.198686,115.0,NaN,NaN
33373,33373,2022-09-15 17:59:00,NaN,11.401396,114.182265,115.0,NaN,NaN
33374,33374,2022-09-15 18:00:00,NaN,11.526471,112.822137,115.0,NaN,NaN
33375,33375,2022-09-15 18:01:00,NaN,11.307124,116.986561,115.0,NaN,NaN
33376,33376,2022-09-15 18:02:00,NaN,10.782697,NaN,NaN,NaN,NaN

28_01 à 03_02

In [38]:
data_refus_tamis_janvier = pd.read_excel("De 28_01 à 03_02 2022\Refus Tamis\TB_D80_et_performances_Usine_Janvier_2022.xlsx")
data_refus_tamis_fevrier = pd.read_excel("De 28_01 à 03_02 2022\Refus Tamis\TB_D80_et_performances_Usine_Février_2022.xlsx")

In [39]:
process_refu_tamis(data_refus_tamis_janvier)
process_refu_tamis(data_refus_tamis_fevrier)

In [40]:
print(data_refus_tamis_janvier)
print(data_refus_tamis_fevrier)

        Jours Poste  Refus Tamis +500 en % QA
3  2022-01-01     1                 35.461690
4  2022-01-01     2                 35.461690
5  2022-01-01     3                 25.810000
6  2022-01-02     1                 30.733229
7  2022-01-02     2                 25.703125
..        ...   ...                       ...
91 2022-01-30     2                 20.960000
92 2022-01-30     3                 21.674009
93 2022-01-31     1                 29.179240
94 2022-01-31     2                 29.193206
95 2022-01-31     3                 31.105089

[93 rows x 3 columns]
        Jours Poste  Refus Tamis +500 en % QA
3  2022-02-01     1                 26.205511
4  2022-02-01     2                 27.455296
5  2022-02-01     3                 29.126214
6  2022-02-02     1                 18.786127
7  2022-02-02     2                 23.913043
..        ...   ...                       ...
82 2022-02-27     2                 27.087257
83 2022-02-27     3                 29.128137
84 2022-02-28     1                 25.339690
85 2022-02-28     2                 33.198507
86 2022-02-28     3                 28.062157

[84 rows x 3 columns]

In [41]:
data_28_01_a_03_02=data_28_01_a_03_02.assign(refus_tamis=0)

In [42]:
data_28_01_a_03_02.dtypes

Unnamed: 0              int64
Time                   object
COURANT ValueY        float64
DEBIT EAU ValueY      float64
SP_INT_AUTO ValueY    float64
SOLIDE ValueY         float64
SP_INT ValueY         float64
PUISSANCE ValueY      float64
refus_tamis             int64
dtype: object

In [43]:
data_28_01_a_03_02['Time'] = pd.to_datetime(data_28_01_a_03_02['Time'], format="%Y/%m/%d %H:%M:%S")

In [44]:
add_refus_tamis(data_refus_tamis_janvier,data_28_01_a_03_02)
add_refus_tamis(data_refus_tamis_fevrier,data_28_01_a_03_02)

In [45]:
data_28_01_a_03_02

,Unnamed: 0,Time,COURANT ValueY,DEBIT EAU ValueY,SP_INT_AUTO ValueY,SOLIDE ValueY,SP_INT ValueY,PUISSANCE ValueY,refus_tamis
0,0,2022-01-28 00:00:00,67.253113,10.185185,10.0,121.003326,120.0,576.604736,20.852708
1,1,2022-01-28 00:01:00,67.253113,10.185185,10.0,121.003326,120.0,576.604736,20.852708
2,2,2022-01-28 00:02:00,67.253113,10.185185,10.0,121.003326,120.0,576.604736,20.852708
3,3,2022-01-28 00:03:00,67.253113,10.185185,10.0,121.003326,120.0,576.604736,20.852708
4,4,2022-01-28 00:04:00,67.253113,10.185185,10.0,121.003326,120.0,576.604736,20.852708
...,...,...,...,...,...,...,...,...,...
11096,11096,2022-02-04 16:56:00,66.443994,9.648076,9.5,NaN,NaN,562.365687,25.668099
11097,11097,2022-02-04 16:57:00,66.702970,9.724392,9.5,NaN,NaN,570.214521,25.668099
11098,11098,2022-02-04 16:58:00,66.539776,9.275415,9.5,NaN,NaN,565.358756,25.668099
11099,11099,2022-02-04 16:59:00,67.152340,8.460648,9.5,NaN,NaN,575.820535,25.668099
11100,11100,2022-02-04 17:00:00,67.503427,9.447209,9.5,NaN,NaN,572.784298,25.668099

Arranger dans une seule dataset

In [46]:
print(data_28_01_a_03_02)
print(data_11_02_a_17_02)
print(data_23_08_a_15_09)
print(data_15_09_a_20_10)

       Unnamed: 0                Time  COURANT ValueY  DEBIT EAU ValueY  \
0               0 2022-01-28 00:00:00       67.253113         10.185185
1               1 2022-01-28 00:01:00       67.253113         10.185185
2               2 2022-01-28 00:02:00       67.253113         10.185185
3               3 2022-01-28 00:03:00       67.253113         10.185185
4               4 2022-01-28 00:04:00       67.253113         10.185185
...           ...                 ...             ...               ...
11096       11096 2022-02-04 16:56:00       66.443994          9.648076
11097       11097 2022-02-04 16:57:00       66.702970          9.724392
11098       11098 2022-02-04 16:58:00       66.539776          9.275415
11099       11099 2022-02-04 16:59:00       67.152340          8.460648
11100       11100 2022-02-04 17:00:00       67.503427          9.447209

       SP_INT_AUTO ValueY  SOLIDE ValueY  SP_INT ValueY  PUISSANCE ValueY  \
0                    10.0     121.003326          120.0        576.604736
1                    10.0     121.003326          120.0        576.604736
2                    10.0     121.003326          120.0        576.604736
3                    10.0     121.003326          120.0        576.604736
4                    10.0     121.003326          120.0        576.604736
...                   ...            ...            ...               ...
11096                 9.5            NaN            NaN        562.365687
11097                 9.5            NaN            NaN        570.214521
11098                 9.5            NaN            NaN        565.358756
11099                 9.5            NaN            NaN        575.820535
11100                 9.5            NaN            NaN        572.784298

       refus_tamis
0        20.852708
1        20.852708
2        20.852708
3        20.852708
4        20.852708
...            ...
11096    25.668099
11097    25.668099
11098    25.668099
11099    25.668099
11100    25.668099

[11101 rows x 9 columns]
      Unnamed: 0                Time  COURANT ValueY  DEBIT EAU ValueY  \
0              0 2022-02-11 00:00:00       65.442617          9.366681
1              1 2022-02-11 00:01:00       65.784166          8.775439
2              2 2022-02-11 00:02:00       65.831569          9.686415
3              3 2022-02-11 00:03:00       64.970144          9.813006
4              4 2022-02-11 00:04:00       65.341595          9.897039
...          ...                 ...             ...               ...
9536        9536 2022-02-17 14:56:00       66.063068          9.216323
9537        9537 2022-02-17 14:57:00       65.189325          9.203489
9538        9538 2022-02-17 14:58:00       66.403390          9.226007
9539        9539 2022-02-17 14:59:00       66.516785          9.297878
9540        9540 2022-02-17 15:00:00       66.288485          9.106144

      SOLIDE ValueY  SP_INT ValueY  PUISSANCE ValueY  refus_tamis
0        115.298274          115.0        559.952023    24.644106
1        113.518156          115.0        562.290662    24.644106
2        113.878942          115.0        562.912594    24.644106
3        117.350561          115.0        557.878828    24.644106
4        113.183894          115.0        561.615206    24.644106
...             ...            ...               ...          ...
9536     111.649853            NaN        564.337326    18.021980
9537     110.982478            NaN        558.512230    18.021980
9538     109.076022            NaN        569.896756    18.021980
9539     109.423127            NaN        569.889818    18.021980
9540     111.625476            NaN        573.881831    18.021980

[9541 rows x 8 columns]
       Unnamed: 0                Time  COURANT ValueY  DEBIT EAU ValueY  \
0               0 2022-08-23 13:46:00             NaN               NaN
1               1 2022-08-23 13:47:00             NaN               NaN
2               2 2022-08-23 13:48:00             NaN               NaN
3               3 2022-08-23 13:49:00             NaN               NaN
4               4 2022-08-23 13:50:00             NaN               NaN
...           ...                 ...             ...               ...
33372       33372 2022-09-15 17:58:00             NaN         11.085793
33373       33373 2022-09-15 17:59:00             NaN         11.401396
33374       33374 2022-09-15 18:00:00             NaN         11.526471
33375       33375 2022-09-15 18:01:00             NaN         11.307124
33376       33376 2022-09-15 18:02:00             NaN         10.782697

       SOLIDE ValueY  SP_INT ValueY  PUISSANCE ValueY  refus_tamis
0                NaN            NaN        586.605394    18.004329
1                NaN            NaN        592.525067    18.004329
2                NaN            NaN        583.371907    18.004329
3                NaN            NaN        592.231900    18.004329
4                NaN            NaN        580.151609    18.004329
...              ...            ...               ...          ...
33372     116.198686          115.0               NaN          NaN
33373     114.182265          115.0               NaN          NaN
33374     112.822137          115.0               NaN          NaN
33375     116.986561          115.0               NaN          NaN
33376            NaN            NaN               NaN          NaN

[33377 rows x 8 columns]
       Unnamed: 0                Time  COURANT ValueY  DEBIT EAU ValueY  \
0               0 2022-09-15 14:40:00             NaN               NaN
1               1 2022-09-15 14:41:00             NaN               NaN
2               2 2022-09-15 14:42:00             NaN               NaN
3               3 2022-09-15 14:43:00             NaN               NaN
4               4 2022-09-15 14:44:00             NaN               NaN
...           ...                 ...             ...               ...
50537       50537 2022-10-20 16:57:00             NaN               NaN
50538       50538 2022-10-20 16:58:00             NaN               NaN
50539       50539 2022-10-20 16:59:00             NaN               NaN
50540       50540 2022-10-20 17:00:00             NaN               NaN
50541       50541 2022-10-20 17:01:00             NaN               NaN

       SOLIDE ValueY  PUISSANCE ValueY  refus_tamis
0         114.791306               NaN          NaN
1         116.841270               NaN          NaN
2         114.797431               NaN          NaN
3         114.255771               NaN          NaN
4         117.610444               NaN          NaN
...              ...               ...          ...
50537            NaN        507.211636    19.740854
50538            NaN        511.160186    19.740854
50539            NaN        509.005283    19.740854
50540            NaN        510.360491    19.740854
50541            NaN        509.105051    19.740854

[50542 rows x 7 columns]

In [47]:
print(data_28_01_a_03_02.shape)
print(data_11_02_a_17_02.shape)
print(data_23_08_a_15_09.shape)
print(data_15_09_a_20_10.shape)

(11101, 9)
(9541, 8)
(33377, 8)
(50542, 7)

In [48]:
print(data_28_01_a_03_02.columns)
print(data_11_02_a_17_02.columns)
print(data_23_08_a_15_09.columns)
print(data_15_09_a_20_10.columns)

Index(['Unnamed: 0', 'Time', 'COURANT ValueY', 'DEBIT EAU ValueY',
       'SP_INT_AUTO ValueY', 'SOLIDE ValueY', 'SP_INT ValueY',
       'PUISSANCE ValueY', 'refus_tamis'],
      dtype='object')
Index(['Unnamed: 0', 'Time', 'COURANT ValueY', 'DEBIT EAU ValueY',
       'SOLIDE ValueY', 'SP_INT ValueY', 'PUISSANCE ValueY', 'refus_tamis'],
      dtype='object')
Index(['Unnamed: 0', 'Time', 'COURANT ValueY', 'DEBIT EAU ValueY',
       'SOLIDE ValueY', 'SP_INT ValueY', 'PUISSANCE ValueY', 'refus_tamis'],
      dtype='object')
Index(['Unnamed: 0', 'Time', 'COURANT ValueY', 'DEBIT EAU ValueY',
       'SOLIDE ValueY', 'PUISSANCE ValueY', 'refus_tamis'],
      dtype='object')

Delete des colonne : {"SP_INT_AUTO ValueY","SP_INT ValueY"} car ce sont des colonne qui n'existent pas dans tous les sous-datasets

In [49]:
data_28_01_a_03_02.drop(["Unnamed: 0","SP_INT_AUTO ValueY","SP_INT ValueY"], axis=1,inplace=True)
data_11_02_a_17_02.drop(["Unnamed: 0","SP_INT ValueY"], axis=1,inplace=True)
data_23_08_a_15_09.drop(["Unnamed: 0","SP_INT ValueY"], axis=1,inplace=True)
data_15_09_a_20_10.drop("Unnamed: 0", axis=1,inplace=True)

In [50]:
print(data_28_01_a_03_02.columns)
print(data_11_02_a_17_02.columns)
print(data_23_08_a_15_09.columns)
print(data_15_09_a_20_10.columns)

Index(['Time', 'COURANT ValueY', 'DEBIT EAU ValueY', 'SOLIDE ValueY',
       'PUISSANCE ValueY', 'refus_tamis'],
      dtype='object')
Index(['Time', 'COURANT ValueY', 'DEBIT EAU ValueY', 'SOLIDE ValueY',
       'PUISSANCE ValueY', 'refus_tamis'],
      dtype='object')
Index(['Time', 'COURANT ValueY', 'DEBIT EAU ValueY', 'SOLIDE ValueY',
       'PUISSANCE ValueY', 'refus_tamis'],
      dtype='object')
Index(['Time', 'COURANT ValueY', 'DEBIT EAU ValueY', 'SOLIDE ValueY',
       'PUISSANCE ValueY', 'refus_tamis'],
      dtype='object')

Maintenant on va arranger afin d'obtenir notre dataset

In [51]:
frames = (data_28_01_a_03_02 , data_11_02_a_17_02 , data_23_08_a_15_09 , data_15_09_a_20_10)
all_data = pd.concat(frames, ignore_index=True)
all_data

,Time,COURANT ValueY,DEBIT EAU ValueY,SOLIDE ValueY,PUISSANCE ValueY,refus_tamis
0,2022-01-28 00:00:00,67.253113,10.185185,121.003326,576.604736,20.852708
1,2022-01-28 00:01:00,67.253113,10.185185,121.003326,576.604736,20.852708
2,2022-01-28 00:02:00,67.253113,10.185185,121.003326,576.604736,20.852708
3,2022-01-28 00:03:00,67.253113,10.185185,121.003326,576.604736,20.852708
4,2022-01-28 00:04:00,67.253113,10.185185,121.003326,576.604736,20.852708
...,...,...,...,...,...,...
104556,2022-10-20 16:57:00,NaN,NaN,NaN,507.211636,19.740854
104557,2022-10-20 16:58:00,NaN,NaN,NaN,511.160186,19.740854
104558,2022-10-20 16:59:00,NaN,NaN,NaN,509.005283,19.740854
104559,2022-10-20 17:00:00,NaN,NaN,NaN,510.360491,19.740854
104560,2022-10-20 17:01:00,NaN,NaN,NaN,509.105051,19.740854

In [53]:
print(all_data['Time'].min())
print(all_data['Time'].max())

2022-01-28 00:00:00
2022-10-20 17:01:00

In [55]:
all_data.to_csv("all_data.csv",index=False)